### ISSUE TITLE
bug: Drop postgres-cdc table should remove replication slot together

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#10027]
### Describe the bug

```sql
CREATE TABLE t (
   id integer,
   a integer,
   b integer,
   c integer,
   PRIMARY KEY (id)
) WITH (
connector = 'postgres-cdc',
....
);

drop table t;
```

Check upstream Postgres.
```sql
SELECT * FROM pg_replication_slots;
```

**Comment by StrikeW** [comment]
By design, the connection node is stateless, so it doesn't provide an interface (e.g. drop) for clean-up stuff. So from the connector node's perspective, it doesn't aware that the `Table` has been dropped. It only knows whether the connection to CN is healthy or not.
If we need to handle this clean-up stuff, the connector node needs to provide an additional interface that would be called during the process of `DROP TABLE`. cc @fuyufjh @BugenZhao @tabVersion

**Comment by StrikeW** [comment]
Considering besides Postgres, other databases (e.g. [yugabyte](https://docs.yugabyte.com/preview/architecture/docdb-replication/change-data-capture/)) may also allocate resources for the replication of CDC events that need to be released explicitly. I think we should add a `Drop` interface to clean up external resources in the connector node, which would be called by Meta in the process of `DROP TABLE`. cc @WillyKidd

**Comment by hzxa21** [comment]
@StrikeW Any updates?

**Comment by StrikeW** [comment]
> @StrikeW Any updates?


I'd like to revisit this issue after https://github.com/risingwavelabs/risingwave/issues/11079 has been done. Right now its priority is low IMO.

**Comment by StrikeW** [comment]
In theory, we should only drop the slot if it is created automatically by us, but we don't distinguish whether the replication slot is created by us or supply via `slot.name`, so I think we should not drop the slot and leave it to user for cleanup.
