### ISSUE TITLE
tracking: support for Grafana

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#10134]
### Is your feature request related to a problem? Please describe.

The remaining works:

- [x] information_schema.columns https://www.postgresql.org/docs/current/infoschema-columns.html
  - [x] ordinal_position
  - [x] udt_name
- [x] #10135
- [x] #10051 

The original queries:

```
SELECT quote_ident(table_name) FROM information_schema.tables WHERE
quote_ident(table_schema) IN (
  SELECT
    CASE WHEN trim(s[i]) = '"$user"' THEN user ELSE trim(s[i]) END
  FROM
    generate_series(
      array_lower(string_to_array(current_setting('search_path'),','),1),
      array_upper(string_to_array(current_setting('search_path'),','),1)
    ) as i,
    string_to_array(current_setting('search_path'),',') s
) ORDER BY table_name limit 100;
```

**Comment by yezizp2012** [comment]
```sql
SELECT quote_ident(table_name) FROM information_schema.tables WHERE
quote_ident(table_schema) IN (
  SELECT
    CASE WHEN trim(s[i]) = '"$user"' THEN user ELSE trim(s[i]) END
  FROM
    generate_series(
      array_lower(string_to_array(current_setting('search_path'),','),1),
      array_upper(string_to_array(current_setting('search_path'),','),1)
    ) as i,
    string_to_array(current_setting('search_path'),',') s
) ORDER BY table_name limit 100;
```
In this SQL, we can see that PostgreSQL can bind `string_to_array` as a table with a single value under column `s`. And actually PostgreSQL will bind the alias in two different ways if provided, take `generate_series` as example:
```
postgres=# select a from generate_series(1, 5) a; // a will bind to column.
 a
---
 1
 2
 3
 4
 5
(5 rows)

postgres=# select a.a from generate_series(1, 5) a; // a will bind to a table a with column a.
 a
---
 1
 2
 3
 4
 5
(5 rows)
```
But in rw, we don't allow to bind scalar function in `from` section, and the infer column name will always be the function name. To achieve that, two major changes are needed in the frontend:
1. be able to bind scalar function as table function, it will return a table with one row and one column named after the alias (if provided) or the function name.
2. dynamically bind the column names of the query, bind to the alias if provided.

Cc @xxchan , Could you help with this if you have time? Since you are more familiar with the table function piece. 🙏

**Comment by xxchan** [comment]
It seems this is already supported in RisingWave.

```
dev=> select range.range, t.x from range(1,2), t;
 range | x
-------+---
     1 | 1
     1 | 2
     1 | 3
```

**Comment by xxchan** [comment]
Oh, the alias handling is wrong

```
select * from range(1,2) as a;
 range
-------
     1
(1 row)
```

**Comment by xiangjinwu** [comment]
```
  SELECT
    CASE WHEN trim(s[i]) = '"$user"' THEN user ELSE trim(s[i]) END
  FROM
    generate_series(
      array_lower(string_to_array(current_setting('search_path'),','),1),
      array_upper(string_to_array(current_setting('search_path'),','),1)
    ) as i,
    string_to_array(current_setting('search_path'),',') s
```
Just FYI this subquery has a simpler form for PostgreSQL >= 14, thanks to the introduction of `string_to_table` function. I did not confirm in grafana whether it would use this if the server declares to support this function.
```
SELECT
    CASE WHEN trim(s) = '"$user"' THEN user ELSE trim(s) END
FROM
    string_to_table(current_setting('search_path'),',') s;
```
