### ISSUE TITLE
feat: support dotnet Postgres client Npgsql

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#10177]
Now it ended up with the following error

```
QueryError: Catalog error: table or source not found: pg_proc
```

**Comment by xiangjinwu** [comment]
```
LEFT JOIN pg_proc AS proc ON proc.oid = typ.typreceive
```

The `typreceive` column refers to functions that parses a type's binary format, which are usually not exposed as user callable (`array_recv`). The existing `FUNC_SIG_MAP` would not be helpful for this query. Rather than implementing `pg_proc` based on `FUNC_SIG_MAP`, I would suggest focus on what this query need first.
