### ISSUE TITLE
feat: Avoid inserting back operator cache for hash join if the cache entry is too large.

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#10979]
### Is your feature request related to a problem? Please describe.

The cache entry could potentially be quite large, especially when considering scenarios where a fact table is joined with a dimensional table. In such cases, any updates made to the dimensional table would require fetching rows from the fact table, resulting in a significant amplification of rows - possibly reaching into the thousands or even hundreds of thousands. To address this issue, my proposal suggests avoiding inserting these rows back into the LRU cache if the row number exceeds a threshold (e.g.  10000). Make it a configurable option `max_cache_entry_size_for_join`.
https://github.com/risingwavelabs/risingwave/blob/95876460e00e242e800de4aff1cc723c79687bce/src/stream/src/executor/hash_join.rs#L1137-L1138

**Comment by BugenZhao** [comment]
This makes sense because the updates to the dimensional table seem too ad-hoc or occasional in this case and it's not worthwhile caching all these rows.

BTW, to further reduce the memory usage and also the latency, I guess we can even make `hash_eq_match` return a `Stream` instead of collecting the rows into an entry before we can yield them.

**Comment by fuyufjh** [comment]
@yuhao-su Ping

**Comment by fuyufjh** [comment]
The Won'https://github.com/risingwavelabs/risingwave/pull/12615#issuecomment-1744372874 is not significant. Let me close it.
