### ISSUE TITLE
`count(*) from pg_matviews` takes 6-7 seconds, is it expected?

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#11219]
```
dev=> select count(*) from pg_matviews;
 count 
-------
   575
(1 row)

Time: 6893.474 ms (00:06.893)
dev=> select count(*) from pg_matviews;
 count 
-------
   575
(1 row)

Time: 7130.653 ms (00:07.131)
```

Is it because every time RW has to get it from `etcd` and `etcd` has to get it from disk?
I thought the second time would take much less time due to caching if there is, but seems no?

**Comment by yezizp2012** [comment]
In the very early version we added some extra columns in `pg_matviews` including `matviewgraph`, which is the json-encoded graph data of the mv and read from meta side. Even though all these infos are cached in memory, but this data size is very large and proportional to the number of mvs and parallelism. I think this's the root cause of it. Currently I'm working on some refactoring on the system catalog and gonna deprecate the column. 
FYI, to get the mv numbers you can use the system table `rw_materialized_views` instead.

**Comment by lmatz** [comment]
Thanks!

```
dev=> select count(*) from rw_materialized_views;
 count 
-------
   575
(1 row)

Time: 2.314 ms
```
super fast
