### ISSUE TITLE
storage(compaction): unstable compaction rate for each LSM-tree layer

### ISSUE THREAD

**Issue by MrCroxx** [risingwavelabs/risingwave#11261]
### Describe the bug

The increment of SSTable count in each layer is not stable with q20.

<img width="954" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/22407295/69cdec71-6521-4cef-902b-0cd45f38269e">

Internal grafana link: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4a/risingwave-dev-dashboard-foyer?orgId=1&from=1690360588367&to=1690364921098

### To Reproduce

nexmark q20

### Expected behavior

The increment of SSTable count in each layer should be stable, and compaction task should be balanced.

### How did you deploy RisingWave?

With `kube-bench`.

### The version of RisingWave

With `foyer-storage` as file cache on branch `xx/tiered-cache-foyer-storage`

**Comment by hzxa21** [comment]
cc @Little-Wallace 

Feel free to reassign.

**Comment by Little-Wallace** [comment]
This is a long time task to make sure that the compaction speed be stable and make LSM-Tree balanced for us.  The most important work at now is to speed up base level compaction, and it is still in progress.
But for test mentioned by this issue, I think it is due to the CPU resource of compactor is not enough....

**Comment by Little-Wallace** [comment]
After increase CPU resource this problem has been solved
