### ISSUE TITLE
feature request: postgres sink: write varchar to UUID type

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11373]
### Is your feature request related to a problem? Please describe.

Background: https://risingwave-community.slack.com/archives/C03BW71523T/p1690898794959069?thread_ts=1690894820.673519&cid=C03BW71523T

### Describe the solution you'd like

https://www.postgresql.org/docs/current/datatype-uuid.html

**Comment by xiangjinwu** [comment]
It seems the slack thread is about ability to sink a varchar-typed field into a uuid-typed field, rather than support uuid type inside RisingWave. The latter is one of the solutions.

**Comment by StrikeW** [comment]
Hmm, right now our sink is strongly-typed which means a `varchar` will be sinked out as a `varchar` (e.g. VARCHAR or LONGVARCHAR in JDBC type). If we want to sink out a `varchar` as `UUID` we need to do type casting. Do we need to add this special type casting case for downstream UUID type? Maybe support UUID in RW is better?

**Comment by xiangjinwu** [comment]
* Supporting UUID in RW is better when we want to ensure invalid data are caught earlier during computation rather than during the sink cast
* The ability to cast during sink may be necessary in more cases
  * When the sink is not PostgreSQL and there is no perfect 1-to-1 mapping between the types
  * Sinking a RW varchar column into a PG varchar / text column. Do we currently support both of these?

**Comment by fuyufjh** [comment]
> The ability to cast during sink may be necessary in more cases

+1. For non-postgresql-comptaible systems, this is obvious because there is no strict data type mapping between multiple systems. 

Even with PostgresQL, it's quite normal to store UUID in string or vice versa. 

I think we can simply loose the checking here. I guess `insert into (x) values ('<some_uuid_number>')` will work whenever x is UUID or VARCHAR.

**Comment by StrikeW** [comment]
> The ability to cast during sink may be necessary in more cases

To be clear, currently, we don't handle **unsafe** type casting in the connector. [We use JDBC API to set parameters for the INSERT statement](https://github.com/risingwavelabs/risingwave/blob/4f599ce147c9cdc06cb3f177b8a79ffb9305e94b/java/connector-node/risingwave-sink-jdbc/src/main/java/com/risingwave/connector/jdbc/PostgresDialect.java#L88-L116), potential (safe) type casting is delegated to the specific drivers. For example, when we sink out a VARCHAR to downstream TEXT, we use the `setString` of JDBC API, the driver will handle the VARCHAR to TEXT mapping under the hood.

Unsafe means inserting a VARCHAR to UUID column may fail if the value of VARCHAR column is in invalid format. Because we need to parse the String into a UUID object via `java.util.UUID.fromString()`, then call `setObject()` to bind the value to be inserted to downstream.

**Comment by xiangjinwu** [comment]
Did some investigation on the current jdbc postgres sink:
* It is okay to sink `varchar` into both `varchar` and `text`.
* Sinking `varchar` into `uuid` requires more effort than into `text`
  * need to pass `java.util.UUID` rather than `java.lang.String`
  * this conversion process may fail
* It is allowed to sink `int` into `int`, `bigint` or even `smallint`
  * `out of range` error may occur in the `smallint` case

The postgres jdbc driver have 3 different ways of identifying a parameter's data type:
|Type|TypeName|ClassName|
|-|-|-|
|12|varchar|java.lang.String|
|12|text|java.lang.String|
|1111|uuid|java.util.UUID|
|4|int4|java.lang.Integer|
|5|int2|java.lang.Integer|
|-5|int8|java.lang.Long|

* `varchar` and `text` share the same Type number and ClassName, which is different from `uuid`'s. So it seems reasonable to accept `text` but reject `uuid` to interoperate.
* However, `int4` and `int8` also have different Type number and ClassName, but are allowed to interoperate by pgjdbc.
* `int4` and `int2` have same ClassName but different Type number. This casting could fail but still allowed.
* It seems that pgjdbc does no check but passes whatever value given to postgres server. The server allows **assignment** cast int4 -> int2 with possible runtime error, but the cast from varchar to uuid is **explicit**.

Conclusion:
* It is possible to allow sinking varchar into uuid, at the cost of writing a special casting for it and handle errors here properly.
* If we do not want fallible casting in sink, we should reject int4 -> int2 here.
* Let's just decide whether these sink casts are allowed to produce error, even when sinking to non-postgres

**Comment by xiangjinwu** [comment]
I agree it is better to avoid error during sink when possible.

Talking about the uuid type specifically, it allows us to use 16 bytes rather than 36+4 bytes per value. But there are no more functions defined to process it. It is a good-to-have optimization, but not necessary.

And sorry for extending the problem to all sink casts. To address the concern of imperfect type match and non-pg database:
* casts are still allowed when unavoidable
* casts are not allowed when there is a better match. In this case `varchar` is a better match so `uuid` is not allowed. Either the sink PG table need to accept `varchar` (and validate afterwards), or RW supports `uuid` natively. We do not intend to support additional external types by maintaining an extensive conversion map in sink.

Does this strategy make sense? If yes I would change the issue back to support uuid type. The user seems to be okay with using `varchar` temporarily.

**Comment by StrikeW** [comment]
> * casts are still allowed when unavoidable

Agreed. For example if user want to sink a `Array` to MySQL, currently we just fallback to concat each item of the array to a string, e.g. "aaa,bbb,ccc". And user should define the downstream column to a data type that can accept string.

> * casts are not allowed when there is a better match.
>   
>   * In this case `varchar` is a better match so `uuid` is not allowed. Either the sink PG table need to accept `varchar` (and validate afterwards), or RW supports `uuid` natively. We do not intend to support additional external types by maintaining an extensive conversion map in sink.
>   * In the case of `int4` -> `int2`, it is also unintended and we would not claim we support/allow it.

Agreed.   cc @fuyufjh

**Comment by fuyufjh** [comment]
Acceptable to me. Anyway, I don't think UUID type is very popular.

By the way, fixing #11374 will also improve the user experience a lot regarding this case.

**Comment by fuyufjh** [comment]
Reopened due to our Slack discussion
