### ISSUE TITLE
Discussion: Optionally integrate Java UDF coprocessor with connector node?

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#11487]
## Motivation

* Many users don't want to deploy the coprocessor server themselves
* Deploy a local coprocessor can reduce the latency and improve the throughput.
* Deploying two JVMs on one CN node is a bit wasteful of resources.
* Users who use these two features are likely to have a significant overlap. (likely from Flink)

cc @wangrunji0408 @neverchanje @StrikeW

**Comment by xxchan** [comment]
related with https://github.com/risingwavelabs/risingwave/issues/10322

**Comment by StrikeW** [comment]
- IMO, from the user's perspective it is better to distinguish connector and UDF server to two components, because they are two different workload, user (and we) need to monitor the cpu and mem **respectively**.
- In the technical aspect, I think we should employ some isolation technique to share a single JVM. For example, virtualization or multi-tenant on a single JVM to isolate workload and failure.

**Comment by liurenjie1024** [comment]
I don't see much benefit in this proposal. This proposal reduced user's operation efforts a little, but it doesn't not so much since we have k8s operator/helm chart. But I think we should implement #10322 since this way user don't need to deploy java udf server by themselves.
