### ISSUE TITLE
Confusing API `StateTable::iter_key_and_val`

### ISSUE THREAD

**Issue by TennyZhuang** [risingwavelabs/risingwave#11673]
In `StateTable::iter_key_and_val`, the `key: Bytes` and `value: Bytes` stream was returned. However, the key is prefixed with `vnode` encoded, which is easy to be misused.

It'll be better if we have a wrapper for returned key.

**Comment by hzxa21** [comment]
Maybe we should return the `FullKey` struct here. cc @wenym1  What do you think?

**Comment by wenym1** [comment]
> Maybe we should return the FullKey struct here

The `TableKey` in the `FullKey` also contains the vnode. If we want to remove the vnode prefix, we should have a more detailed struct.

**Comment by stdrc** [comment]
😄 Spent a day to debug a bug related to this issue...By using `risingwave_storage::table::merge_sort` to merge sort many iter streams on different vnode, this issue can be significantly amplified, because `merge_sort` hides the `key` from table iterators. IMO, the returned key should not contain vnode prefix, since it's not added by the caller of `iter_key_and_val_with_pk_range`.

**Comment by hzxa21** [comment]
> 😄 Spent a day to debug a bug related to this issue...By using `risingwave_storage::table::merge_sort` to merge sort many iter streams on different vnode, this issue can be significantly amplified, because `merge_sort` hides the `key` from table iterators. IMO, the returned key should not contain vnode prefix, since it's not added by the caller of `iter_key_and_val_with_pk_range`.

Indeed. vnode should be hidden by the state table abstraction. We should fix it.

**Comment by stdrc** [comment]
Guess this can be closed by #11880?

**Comment by hzxa21** [comment]
> Guess this can be closed since #11880 has been merged?

Yes. Thanks for the reminder.
