### ISSUE TITLE
bug(expr): `case when` containing table functions allowed but returning wrong results

### ISSUE THREAD

**Issue by curiosityyy** [risingwavelabs/risingwave#11905]
### Describe the bug

```
dev=> SELECT
    CASE
      WHEN array_length(array[]::INTEGER[]) = 0 THEN NULL
      WHEN array_length(array[]::INTEGER[]) > 0 THEN jsonb_array_elements('[{"a": 3, "b": 4}]'::jsonb)
    END AS a;
 a
---

(1 row)

dev=> SELECT
    CASE
      WHEN array_length(array[]::INTEGER[]) = 0 THEN NULL
      WHEN array_length(array[]::INTEGER[]) > 0 THEN jsonb_array_elements('[]'::jsonb)
    END AS a;
 a
---
(0 rows)
```

**Comment by BugenZhao** [comment]
In Postgres:

```
ERROR:  set-returning functions are not allowed in CASE
LINE 4: ... WHEN array_length(array[]::INTEGER[],1) > 0 THEN jsonb_arra...
                                                             ^
HINT:  You might be able to move the set-returning function into a LATERAL FROM item.
```

**Comment by xiangjinwu** [comment]
`CASE WHEN` (and `COALESCE`) is special here because they are expected to evaluate their arguments lazily (#6202). As an example, common sub-expression extraction skips visiting their arguments:
https://github.com/risingwavelabs/risingwave/blob/4746016469e4200d20bf83438d330b5d70636f12/src/frontend/src/optimizer/plan_expr_visitor/expr_counter.rs#L56-L62

However for the evaluation of set-returning functions, they are always extracted to a child `ProjectSet` node and evaluated before their parent `Project` node containing `CASE WHEN` - this goes against the short-circuit expectation and thus [banned by PostgreSQL](https://github.com/postgres/postgres/blob/REL_15_4/src/backend/parser/parse_expr.c#L1672). To contrast with, aggregate functions are also extract to child `Aggregate` node and evaluated first, but this tricky behavior is documented rather than banned.

Some related notes:
* PostgreSQL [does not guarantee](https://www.postgresql.org/docs/15/sql-expressions.html#SYNTAX-EXPRESS-EVAL) the short-circuit behavior of `AND`/`OR`. Only `CASE WHEN` and `COALESCE` works with some caveats (incl. srf, const, agg). This gives the optimizer more flexibility to transform equivalent boolean expressions, and it is likely our optimizer is already breaking the short-circuit behavior (esp. `AND`).
* The places where set-returning functions are (dis)allowed are not aligned between [PostgreSQL](https://github.com/postgres/postgres/blob/REL_15_4/src/backend/parser/parse_func.c#L2512) and [RisingWave](https://github.com/risingwavelabs/risingwave/blob/9acfac97f7e93b755c615f2550cdf87d809645b5/src/frontend/src/binder/expr/function.rs#L1288), for example `HAVING`, `FILTER` and `JOIN ON`.
* In addition to set-returning functions and aggregate functions, other [special "expressions"](https://github.com/risingwavelabs/risingwave/blob/9acfac97f7e93b755c615f2550cdf87d809645b5/src/frontend/src/expr/mod.rs#L120-L123) may also behave unintuitively: subquery, window functions

**Comment by fuyufjh** [comment]
> * The places where set-returning functions are (dis)allowed are not aligned between [PostgreSQL](https://github.com/postgres/postgres/blob/REL_15_4/src/backend/parser/parse_func.c#L2512) and [RisingWave](https://github.com/risingwavelabs/risingwave/blob/9acfac97f7e93b755c615f2550cdf87d809645b5/src/frontend/src/binder/expr/function.rs#L1288), for example `HAVING`, `FILTER` and `JOIN ON`.

Then, shall we change the RW's behavior to be consistent with PG? From my understanding, set-returning function is quite tricky, and it looks even more tricky when being placed inside an row expression, so let's ban it.
