### ISSUE TITLE
discussion: shall we introduce `WITH` properties for materialized views?

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#11929]
Shall we introduce a `WITH` clause for `create materialized view` statement?

We have `WITH` for tables, source, and sink to define some additional parameters. However, currently there is no such place for materialized views.

For example, `rate_limit` should be a per-stream property and should be able to be viewed and modified after MV creation. See also https://github.com/risingwavelabs/risingwave/pull/11919#issuecomment-1696731719. But this motivation seems not strong enough, because it's designed as a makeshift in case of creating MV failure.

**Comment by kwannoel** [comment]
Minor improvement to UX: clearer semantics for session variables associated to MV.
Things like `RW_TWO_PHASE_AGG`, `STREAMING_PARALLELISM` can be tagged to specific MV, as per their semantics.

**Comment by fuyufjh** [comment]
- `RW_TWO_PHASE_AGG` may be not the case? It is an optimizer hint and applies to batch query as well.
- `STREAMING_PARALLELISM`. Yeah, we can move the scale out/in commands here. Modifying the parallelism means scaling.

**Comment by kwannoel** [comment]
> RW_TWO_PHASE_AGG may be not the case? It is an optimizer hint and applies to batch query as well.

My take is that as with global variables, setting session variables means the user may mistakenly use `two_phase_agg` with all queries in the session.

If they can scope it to a materialized view, it is less likely they make this mistake.

**Comment by st1page** [comment]
maybe all session variable can be defined here for the query to overwrite the session varible such as timezone?

**Comment by fuyufjh** [comment]
> maybe all session variable can be defined here for the query to overwrite the session varible such as timezone?

Good point. At least timezone sounds good to me.

Another random thought: how about capturing these session variables into the `WITH` clause automatically? It seems to be an elegant way to persist these variables (I don't know how it was done in current implementation). Additionally, when users run `show create materialized view`, the context can be printed as well.

**Comment by BugenZhao** [comment]
Just FYI, we already have a context structure for each streaming job:

https://github.com/risingwavelabs/risingwave/blob/b823b0ce7b68f032c00e03d4cdda95bdd6a9f1b4/proto/stream_plan.proto#L723-L728

We can consolidate them in one place, such as storing all session-local variables here or in the `WITH` clause of the definition.

**Comment by BugenZhao** [comment]
Recently, I have been considering how to achieve the best availability for altering streaming jobs and have come up with similar ideas. It turns out we have to apply the same set of session variables to produce a similar plan with the updated SQL query.

This may also apply to version upgrades. Imagine that there are some new optimization rules introduced in a new release of RisingWave, a slightly updated SQL query may compile into an incompatible plan and then fail to reuse the previous states. However, if we can control the effect of the new rules with a toggle of the session variable, we can automatically instruct the compiler to avoid applying these rules according to the absent entry in the persisted session variables from the previous streaming job.

Even so, we also need to introduce a mechanism to allow users to explicitly update the session variables when altering streaming jobs.

**Comment by st1page** [comment]
maybe related: we need some refactors to achieve a strong type WithOption framework. https://github.com/risingwavelabs/risingwave/issues/9450

**Comment by BugenZhao** [comment]
Some preposed refactoring (like https://github.com/risingwavelabs/risingwave/issues/7034#event-10601936580) might be necessary to avoid getting further messy.

**Comment by fuyufjh** [comment]
As mentioned above, `RW_STREAMING_RATE_LIMIT` seems to be a good starting point

**Comment by xxchan** [comment]
We now already have `create materialized view mv with ( streaming_rate_limit = 200 )` since #13009

**Comment by fuyufjh** [comment]
> We now already have `create materialized view mv with ( streaming_rate_limit = 200 )` since #13009

`Alter` not supported yet.
