### ISSUE TITLE
support `\d "TABLE NAME"`

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12131]
### Is your feature request related to a problem? Please describe.

```
dev=> create table t(v1 int);
CREATE_TABLE
dev=> \d t;
ERROR:  QueryError: Bind error: failed to bind expression: c.relname OPERATOR(pg_catalog.~) '^(t)$' AND pg_catalog.pg_table_is_visible(c.oid)

Caused by:
  Feature is not yet implemented: binary op: PGQualified(QualifiedOperator { schema: Some(Ident { value: "pg_catalog", quote_style: None }), name: "~" })
Tracking issue: https://github.com/risingwavelabs/risingwave/issues/112
```

Did we plan to support this, or plan to use `describe "TABLE NAME"` to replace it? 

Implementing this binary op seems to be a complex task

Reported by a user.

**Comment by TennyZhuang** [comment]
#8966

**Comment by TennyZhuang** [comment]
Seems the only blocker is parsing the OPERATOR syntax.

**Comment by xiangjinwu** [comment]
Duplicate with #5383

> Seems the only blocker is parsing the OPERATOR syntax.

Far from that. Actually the parsing has been done, and it is also easy to bind & support that specific binary operator `~` (supporting all operators without duplicate code requires a refactor).

However, `\d table` intends to display ALL info about a table inside a specific version of PostgreSQL, thus requires a lot of catalog tables and columns. My https://github.com/risingwavelabs/risingwave/issues/5383#issuecomment-1573137335 about missing piece was about PG 8.3. Now we declared to be PG 9.5 and there are more things missing, and this would definitely break again when we upgrade the compatible version again. That is, this feature relies heavily on pg internals of a specific version. Source of `psql` can be checked [here](https://github.com/postgres/postgres/blob/REL_15_4/src/bin/psql/describe.c#L1515).

Closing as duplicate rather than as wont fix. We may consider how to systematically support most catalog tables before we can do this.
