### ISSUE TITLE
Optimize the count(*) query

### ISSUE THREAD

**Issue by yufansong** [risingwavelabs/risingwave#12191]
### Is your feature request related to a problem? Please describe.

Should we add an optimization for `count(*)`? Its like the most basic query everyone runs and you can probably answer it from metadata alone when there is no WHERE clause.

**Comment by fuyufjh** [comment]
It's impossible to awswer `count(*)` by fecthing metadata only, but you can query from `select * from rw_catalog.rw_table_stats` to get an estimated result. See more: https://docs.risingwave.com/docs/current/rw_catalog/

---------------

If you are interesting, here let me explain why it's impossible to return an accurate `count(*)` result by simply accumulating metadata.

Unlike the append-only formats such as Parquet or ORC, RisingWave is built on an LSM-Tree-based storage, which means records in upper level can override the records in lower level. Even if we record the row count in SST's metadata, the total row number is **not** the sum of all SSTs. 

For example, 

```
in SST-1: (#records = 1)
  key = '1'  val = 'I am updated'

in SST-2: (#records = 2)
  key = '1'  val = 'foo'
  key = '2'  val = 'bar'
```

The content of the table is actually

```
key   val
--------------------
  1   I am updated
  2   bar
```

The total records returned by `count(*)` should be 2 instead of 3.

**Comment by yufansong** [comment]
Thanks for your reply 👍

**Comment by kwannoel** [comment]
Hmm... Seems like hummock has `TableStats` which contains `total_key_count`. That's how we provide the MV backfill progress.

I think it's possible with it?
