### ISSUE TITLE
`Read Merged SSTs` is not shown on the dashboard

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12380]
### Describe the bug

![SCR-20230918-mit](https://github.com/risingwavelabs/risingwave/assets/5791930/c73e739b-6422-42ac-8893-8f5fdcf89edb)
for example: https://grafana.test.risingwave-cloud.xyz/d/EpkBw5W4k/risingwave-dev-dashboard?orgId=1&var-datasource=Prometheus:%20test-useast1-eks-a&from=1694707200000&to=1694793599000&var-namespace=nexmark-3cn-3cm-compactor-3cpu-30min-lmatz&var-instance=benchmark-risingwave&var-node=All&var-job=All&var-table=All

Is it not used anymore or is it broken?

**Comment by zwang28** [comment]
Should be fixed by https://github.com/risingwavelabs/risingwave/pull/12148
`Fix table id filter after https://github.com/risingwavelabs/risingwave/issues/11822 when empty string is used as the table id value.`

What happen in this issue is storage metric level is set to info, so  all `table_id` label is set to "" for `state_store_iter_merge_sstable_counts`. And current grafana conf doesn't display it correctly. If you remove the table_id label in query, data should be displayed correctly.
