### ISSUE TITLE
test: "inline" style connector e2e tests

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#12451]
In https://github.com/risingwavelabs/risingwave/pull/12344, we introduced an "inline" style for writing source e2e tests. Basically, it consists of two points:

- Interacting with external systems by executing system commands with `system ok`.
	https://github.com/risingwavelabs/risingwave/blob/08b72f6f3a3d749f2b0f46f861d5de0fb0b5a3f5/e2e_test/source/cdc_inline/alter/postgres_alter.slt#L3-L7
Furthermore, by setting the environment variables like `PGHOST`, `PGPORT`, `PGPASSWORD`, we can avoid repeating them in the commands.
	
- Using environment variables in SQL. Enable this with `control substitution on`.
	https://github.com/risingwavelabs/risingwave/blob/4f7ea7112c8db6c94c01f762fad1ce1477be608d/e2e_test/source/cdc_inline/alter/postgres_alter.slt#L9-L21
By also leveraging the [canonical environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) with `psql` client, we make the CDC table definition here consistent with the `psql` system commands. Also, setting default values for these variables allows for painless local execution of the test cases.

This can be much clearer and more flexible than writing the test logic in shell scripts inside `ci/scripts`, where `sqllogictest` must be interleaved with `psql` or `mysql` calls. This also empowers the tests with complicated procedures, like schema change on both sides.

**Comment by xxchan** [comment]
More aggressively, to further simplify the test scripts, I think we don't need to provide a default value at all. As mentioned https://github.com/risingwavelabs/risingwave/issues/15995#issuecomment-2029171270, it can be loaded via `risedev slt`.

And we can define a large env var like
```
WITH_OPTIONS_PG="
     connector = 'postgres-cdc', 
     hostname = '...', 
     port = '...', 
     username = '...', 
     password = '...', 
     database.name = '...'
"
```

**Comment by xxchan** [comment]
I want to elaborate the motivation and some further designs (according to recent discussions with @BugenZhao), to explain why "inline" style is a good idea.


## Motivation

A good test framework should have these characteristics:
1. We can run tests easily both in CI and locally. 
  Otherwise if the setup is too complex for local run, when we need to add new tests or new features (especially if the developer is not the original writer of the tests, or is even new to the module), we will just wait for CI. And if it failed, we just make some new random attempts and pray it works. (**low productivity**) And consequentially, we are not willing to write new tests. (**lack of test cases**) 
2. We can write tests easily.
  Otherwise, we don't want to write new tests. And when we write, we only write very simple cases. (**lack of complex cases**)

We do have all these problems above (bold font).

Our current test pipeline is like this:
The entrypoint is: `ci/scripts/e2e-source-test.sh`. It run some setup scripts or commands, and then run the `slt` test cases.
For each kind of connector (actually even each test cases of the same connector), we run test cases in different commands. This is much worse compared with `'./e2e_test/streaming/**/*.slt'` https://github.com/risingwavelabs/risingwave/blob/8b09aeb30504bcf409b3fc5355d6783d98af89c1/ci/scripts/e2e-source-test.sh#L166-L175


Specifically, the main problems are:

a. Test cases (`slt`) and setup scripts (`sh`) are put in different places. So test cases themselves are not understandable, and not runnable for new developers (even for original authors themselves as time passes by).
  - Note that setup scripts are all over the place: 
  	- `e2e_test/source`
  	- `scripts/source`
  	- `ci/scripts/run-e2e-test.sh`

b. We can only run setup script, and then run test case, instead of **alternately** executing commands between external systems and RisingWave. So some complex scenarios like split change are not well tested.

c. The setup scripts hardcoded ports like `kafka-topics.sh --bootstrap-server message_queue:29092`, so they are not for local run at all.


Now imagine if I'm a new developer, to run a specific `test.slt`, I need to
1. start RisingWave (mainly via `risedev d`)
2. start external service
3. set up data in external service for `test.slt` (if I can find it)
4. run `test.slt`

Note that step 3 & 4 are not always available as the scripts hardcoded the ci env.

## Proposed Solution

The `system` command, as proposed by the original issue, is a good idea to solve most of the problems:
- For problem a, it puts setup scripts and test cases in the same file.
- For problem b, it changes the mindset from "setup scripts" to "commands", making it more composable, and easier to construct more complex cases.
- For problem c, it uses environment variables to make it configurable.

Essentially, it merges previous step 3 & 4:
1. start RisingWave (mainly via `risedev d`)
2. start external service
3. (new step) set environment variables of the external service
4. run `test.slt` (with `system` commands)

It provides a good foundation, but still not perfect enough.
- The new step 3 above is still a little troublesome. We need to find what ports are used by the services, find what env vars are used in the test script, and set it correctly. Can we do it automatically?
- When testing, we usually want to setup a clean environment, or frequently clean the environment. This is not convenient e.g., if we are using Postgres on Mac with `brew services`.

So we can go one step further.

### Enhancement 1: Integrate external services with RiseDev

If a service is managed by RiseDev (more precisely, `risedev-dev`)
- We can save the trouble of setting envvars or CLI args.
  This is inspired by using `risedev psql` to simplify `psql -h localhost -p 4566 -d dev`, and similarly `risedev slt`. (This is achieved by loading `risedev-env` file, which is written when `risedev d` is called)
- We can easily destroy and start a clean environment.

Take the test case in the original post as an example,

https://github.com/risingwavelabs/risingwave/blob/f31698df52575e0e43d11147cf515bac262d325f/e2e_test/source/cdc_inline/alter/postgres_alter.slt#L3-L21

Assume we have `postgres` in `risedev.yml`, then we will write `PGPORT` etc in `risedev-env`, and load `risedev-env in the `slt` task.

With this, our testing workflow will become as simple as:
1. start RisingWave and external services via `risedev d`
2. run `test.slt` via `risedev slt`

#### How to manage external systems in RiseDev?

One challenge is some services are hard to configure and start; another challenge is that CI uses `docker-compose`, but local RiseDev doesn't.

If we restart from scratch now (with lightweight containers like `orb` in Mac), maybe we will choose to let `risedev-dev` be a thin wrapper over `docker-compose`. But changing it requires some hard work now.

The genius idea we have is `user-managed`. Previously we use this to debug RisingWave components; now we can use this to fake the service is managed by RiseDev, and provide necessary environment variables. Alternatively, we may also have something like `risedev-env.user` to provide env vars, but put everything in `risedev.yml` one place can be better. 

In CI, we also don't need to provide a fake `risedev-env` (as we do in some places now), and just use `user-managed` services.

Locally,
- For new services like `mysql`, `postgres`, we can let them be `user-managed` only services.
- In the future, we can support starting them via `docker compose` backend for Risedev. We can do this in a very progressive manner.

### Enhancement 2: Further simplify test script writing with RiseDev envs and commands (optional)

The env vars simplified running tests a lot, but when writing tests, there are still a lot of copy-pasting.

Solution:
- We can define a large env var like below to simplify `WITH` options
	```
	RISEDEV_WITH_OPTIONS_PG_COMMON="
	     connector = 'postgres-cdc', 
	     hostname = '...', 
	     port = '...', 
	     username = '...', 
	     password = '...', 
	     database.name = '...'
	"
	```
- Not all command line tools support environment variables like `psql`, e.g., we might need to copy-paste `kcat -b ${RISEDEV_KAFKA_BOOTSTRAP_BROKERS} ...`. We can simplify this with `risedev kcat`.

### Example: Integrate Kafka

https://github.com/risingwavelabs/risingwave/pull/16244

What's changed in this PR:
- Support `user-managed` kafka in `risedev.yml`. This is mainly for CI env. For local env we have native Kafka.
- Add new `risedev-env` vars: `RISEDEV_KAFKA_BOOTSTRAP_SERVERS`, `RISEDEV_KAFKA_WITH_OPTIONS_COMMON`, `RPK_BROKERS`
- New test https://github.com/risingwavelabs/risingwave/pull/16244/files#diff-1ab35726d1a9569223d3c3460801d24d581cafc8e03371236a4ca2e17e6adf64 uses `rpk` to write `system` commands for Kafka, and `rpk` uses env var `RPK_BROKERS`. It is nothing different from the other "inline" tests like psql.
- Added some helpful `risedev` commands. They can be used by `slt` tests (but not used yet), and also run manually.

## Discussions

One may argue that most of the trouble we have is because the setup `sh` scripts are not well written, and are scattered. If we can rewrite them in a good shape (including supporting local run) and put them in one single place, it will be good enough, and there's no need to introduce a new framework.

Although there are some additional benefits mentioned above that is not achievable by good bash scripts only, the argument makes some sense to me. But my feeling is that this is somehow similar to "with C++ we can do good things, so there's no need to change to Rust". The reality is developers are not good at writing and organizing scripts. With the new framework, developers are encouraged to write composable commands to create complex test scenarios and prepare the setup not only for CI but also for local run.

### Limitations

I don't find anything not achievable yet. Comments are welcome.

**Comment by xxchan** [comment]
P.S. We don’t need to rewrite existing tests into the new style any time soon. We can just write new tests and/or copy-on-write old tests.

P.P.S. I think this idea also applies to sink tests.

**Comment by stdrc** [comment]
> One may argue that most of the trouble we have is because the setup `sh` scripts are not well written, and are scattered. If we can rewrite them in a good shape (including supporting local run) and put them in one single place, it will be good enough, and there's no need to introduce a new framework.

Interestingly, when DocSlt was introduced, you had very similar comment😄: https://github.com/risingwavelabs/risingwave/issues/5117#issuecomment-1237389589.

Btw, I strongly +1 for this proposal, just because of the same reason I introduced DocSlt at that time. Not everyone (actually I think only a few of us) can write good and clean shell scripts, and also many don't like to write comments like "refer to xxx.sh for the source setup process". It can be way more clear to put setup and teardown process together with the test body.

**Comment by StrikeW** [comment]
Is it possibly to execute `risedev kill` or other `risedev` commands in the `.slt` file (aka. the inline style)? Because we also need to test recovery scenario in the e2e source test.

**Comment by xxchan** [comment]
> Is it possibly to execute `risedev kill` and other `risedev` commands in the `.slt` file (aka. the inline style)? Because we also need to test recovery scenario in the e2e source test.

Currently not possbile, because one slt corresponds to one database session. It's possible to extend `sqllogictest-rs` to support sth like `--recreate-session`.

Alternatively, the newly supported `RECOVER` command might be OK, if the frontend is not killed.

**Comment by xxchan** [comment]
Other `risedev` commands is completely OK.

**Comment by xxchan** [comment]
> Interestingly, when DocSlt was introduced, you had very similar comment😄: [#5117 (comment)](https://github.com/risingwavelabs/risingwave/issues/5117#issuecomment-1237389589).

Yes, when I wrote this, I was also thinking about me opposing to DocSlt. 😄 

Actually, the "inline" connector e2e tests have a lot in common with DocSlt:
- very simple idea, and easy to implement (so workload/ROI is not an issue)
- both try to put scattered stuff in one place.

---

I changed my mind about DocSlt because of the fact that DocSlt (perhaps along with @wangrunji0408 's expr macro) together made it much painless to add new expressions -- we just need to change one file for everything. And the result is we added many new (tested) expressions.

So smooth DX matters, a lot. I'd like to quote "[Why Care About Build Times](https://matklad.github.io/2021/09/04/fast-rust-builds.html#Why-Care-About-Build-Times)":

> That being said, compilation time is a *multiplier* for basically everything. Whether you want to ship more features, to make code faster, to adapt to a change of requirements, or to attract new contributors, build time is a factor in that.
> 
> It also is a non-linear factor. Just waiting for the compiler is the smaller problem. The big one is losing the state of the flow or (worse) mental context switch to do something else while the code is compiling. One minute of work for the compiler wastes more than one minute of work for the human.

I'm feeling that testing is also a *multiplier* for developing features.
