### ISSUE TITLE
investigate RW's integration with Migrate

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#12970]
https://github.com/golang-migrate/migrate

There is a PostgreSQL driver in migrate, but it uses some unsupported features such as
lock, transaction, `not null` constraints. https://github.com/golang-migrate/migrate/blob/master/database/postgres/postgres.go

Requested by PoC user

**Comment by fuyufjh** [comment]
We might need to fork the file ([postgres.go](https://github.com/golang-migrate/migrate/blob/master/database/postgres/postgres.go)), to remove the `not null` constaint.

**Comment by twocode** [comment]
Let's come up with a baseline of how RisingWave works with current Migrate before next plan.

**Comment by lmatz** [comment]
Can also refer to https://github.com/golang-migrate/migrate/blob/master/database/clickhouse/clickhouse.go
seems to use much fewer advanced features in the driver.

**Comment by xxchan** [comment]
Forked here https://github.com/xxchan/migrate/pull/1

To test/use it:
```bash
git clone https://github.com/xxchan/migrate && cd migrate && git checkout risingwave
make

./migrate -database "risingwave://postgres@localhost:4566/dev?sslmode=disable" -path database/risingwave/examples/migrations up
./migrate -database "risingwave://postgres@localhost:4566/dev?sslmode=disable" -path database/risingwave/examples/migrations down
```

## Notes about how it works

Basically `migrate` is a very simple tool. (almost close to scripting)

It's just used to go up and down from "versions" (used to recording the history?). No complex guarantees are provided. 

The current state (version) is stored in a dedicated table.

```
v1.down.sql
v1.up.sql
v2.down.sql
v2.up.sql
```

```
migrate up 1       # this just executes v1.up.sql
migrate up 1       # this just executes v2.up.sql
migrate down 1     # this just executes v2.down.sql
```

IMO the advanced features like lock, transaction and `not null` are simply fool-proof instead of must-have, so we can remove them, just like clickhouse's implementation.
