### ISSUE TITLE
Persist the backfill state to record backfill progress

### ISSUE THREAD

**Issue by StrikeW** [risingwavelabs/risingwave#13204]
https://github.com/risingwavelabs/risingwave/pull/12535 doesn’t persist the backfill state yet, it will backfill again during recovery.

**Comment by kwannoel** [comment]
Do we also want to handle recovery for this issue? Seems like this PR only persist the backfill state for cdc executor, but I'm not sure if that's sufficient.

In meta, we need to persist the table fragments and table proto as well. Otherwise they will be lost on recovery.

Similar to https://github.com/risingwavelabs/risingwave/pull/12167

**Comment by StrikeW** [comment]
I take a look of https://github.com/risingwavelabs/risingwave/pull/12167, since `CREATE TABLE` is always `Foreground` (it will return success after collect the initial barrier), so I think we don't need to recover its progress likes `Background` streaming job does.

**Comment by kwannoel** [comment]
> I take a look of https://github.com/risingwavelabs/risingwave/pull/12167, since `CREATE TABLE` is always `Foreground` (it will return success after collect the initial barrier), so I think we don't need to recover its progress likes `Background` streaming job does.

Ah got it. Makes sense to me.
