### ISSUE TITLE
Use `standalone` as default docker compose mode

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#13235]
LGTM

Actually, I think we can go one step further and use standalone mode in Docker by default. That is, instead of adding a new `docker-compose-standalone.yaml`, I think we can place the existing `docker-compose.yaml`, because that a user preferring docker-compose than k8s must want to deploy RW in a single machine.

But this may involve some modifications to test pipeline as well. Since the v1.4 is coming soon, we may do it later.

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/pull/13233#pullrequestreview-1711905391_

**Comment by lmatz** [comment]
cc: @huangjw806 

could you help take a look after `v1.4` is released?

In short, we want to rename the `docker-compose-standalone.yaml` as `docker-compose.yml` (the default one triggered when user `docker compose` under the `docker` folder), but worrying that it may mess up test pipelines on Buildkite.

And rename the current  `docker-compose.yml` to `docker-compose-distributed.yml`

**Comment by huangjw806** [comment]
> In short, we want to rename the `docker-compose-standalone.yaml` as `docker-compose.yml`

Does that mean our integration tests also need to use standalone mode?

**Comment by lmatz** [comment]
use standalone mode. 

We will recommend users to use standalone mode by default once it is integrated into the test pipelines and we found no problem

**Comment by StrikeW** [comment]
> use standalone mode.
> 
> We will recommend users to use standalone mode by default once it is integrated into the test pipelines and we found no problem

@lmatz After change the integration pipeline to use standalone mode, all logs printed by different components (cn, compactor, etc) are interleaved. And we cannot easily grep by component name, since there is no component name prefix in the log only crate prefix. That makes it hard to analyze the failed test case.

So what about change the docker-compose.yml of integration test to inherit from `docker-compose-distributed.yml` instead of `docker-compose.yml`.
