### ISSUE TITLE
hash_join panic in backwards compat test

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#13465]
See compute node logs in https://buildkite.com/risingwavelabs/main-cron/builds/1145#018bd497-981d-4ac5-be67-459c89247f68

```
thread 'risingwave-streaming-actor' panicked at src/stream/src/executor/managed_state/join/join_entry_state.rs:51:13:
pk [0, 128, 0, 0, 0, 85, 165, 162, 158, 0, 0, 0, 0] should be in the cache
thread 'risingwave-streaming-actor' panicked at /risingwave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bytes-1.5.0/src/buf/buf_impl.rs:289:9:
assertion failed: self.remaining() >= 1
thread 'risingwave-streaming-actor' panicked at src/storage/src/mem_table.rs:368:49:
internal error: entered unreachable code: memtable update should always be paired with a storage key
stack backtrace:
2023-11-15T20:37:24.363039515Z ERROR risingwave_stream::task::stream_manager: actor exit actor=184 error=Executor error: Storage error: MemTable error: Inconsistent operation
  backtrace of `StreamExecutorError`:
   0: from
             at ./src/stream/src/executor/error.rs:39:10
   1: into<risingwave_stream::executor::error::ErrorKind, risingwave_stream::executor::error::Inner>
             at /rustc/249624b5043013d18c00f0401ca431c1a6baa8cd/library/core/src/convert/mod.rs:757:9
   2: from
             at ./src/stream/src/executor/error.rs:173:34
```

**Comment by kwannoel** [comment]
Good `main-cron` commit: https://github.com/risingwavelabs/risingwave/commit/e46151bdcb5427ddc7306015d2729a7edda312ce
Bad `main-cron` commit: https://github.com/risingwavelabs/risingwave/commit/1327bb237b079967da35603b684aae9b857a8629

**Comment by BugenZhao** [comment]
Compare the changes here: https://github.com/risingwavelabs/risingwave/compare/e46151b...1327bb2

**Comment by kwannoel** [comment]
First bad commit https://github.com/risingwavelabs/risingwave/commit/3997e2683e858ac65daca52c5a8ab6c24301206b

**Comment by stdrc** [comment]
I tried to revert possible executor schema change (actually unchanged) in https://github.com/risingwavelabs/risingwave/pull/13389, and the test still fails, on `nexmark_q101` more precisely. Then I realizes that this is very likely to be exactly the case that I just mentioned in https://github.com/risingwavelabs/risingwave/issues/13559#issuecomment-1820945754, which is a compatibility issue of https://github.com/risingwavelabs/risingwave/pull/13376. So the first bad commit may be https://github.com/risingwavelabs/risingwave/commit/0020507edbc4010b20aeeb560c7bea9159315602 rather than https://github.com/risingwavelabs/risingwave/commit/3997e2683e858ac65daca52c5a8ab6c24301206b. I started two tests again, let's see.

- https://buildkite.com/risingwavelabs/pull-request/builds/35836 
- https://buildkite.com/risingwavelabs/pull-request/builds/35838

**Comment by stdrc** [comment]
Confirmed: https://buildkite.com/risingwavelabs/pull-request/builds/35838#018bf23d-717c-4b10-9e25-d64c72412e1e, https://github.com/risingwavelabs/risingwave/commit/0020507edbc4010b20aeeb560c7bea9159315602 also fails. And the failing queries are nexmark q7 and q101, both having a `max` function call.
