### ISSUE TITLE
Decouple iceberg commit from risingwave commit.

### ISSUE THREAD

**Issue by liurenjie1024** [risingwavelabs/risingwave#13899]
See https://github.com/risingwavelabs/rfcs/pull/78

**Comment by ZENOTME** [comment]
I find that after decoupling, it means that the data is not necessary to flush when it meets a checkpoint. To keep the original semantics of `flush`, we should need to distinguish it from the regular checkpoints. For regular checkpoint, the sink may not flush the data. But for the checkpoint caused by `flush`, the sink should guarantee to flush the data.

**Comment by liurenjie1024** [comment]
cc @wenym1

**Comment by ZENOTME** [comment]
Following is the modification probably involved:
1. BarrierKind <-- add FlushCheckpoint kind
2. LogWriter::flush_current_epoch  <-- add trigger_by_flush param
3. item for LogStoreIml <-- add trigger_by_flush field
we only need to modify `kv_log_store` because `in_memory log store` can't be used in decouple mode.
4. LogStoreReadItem <-- add trigger_by_flush

**Comment by liurenjie1024** [comment]
> Following is the modification probably involved:
> 
> 1. BarrierKind <-- add FlushCheckpoint kind
> 2. LogWriter::flush_current_epoch  <-- add trigger_by_flush param
> 3. item for LogStoreIml <-- add trigger_by_flush field
>    we only need to modify `kv_log_store` because `in_memory log store` can't be used in decouple mode.
> 4. LogStoreReadItem <-- add trigger_by_flush

LGTM

**Comment by ZENOTME** [comment]
closed by #15634
