### ISSUE TITLE
Bug: json!(f32) cannot get right result

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave#14180]
### Describe the bug

We used json!() in some places to convert f32 to json(such as sink's JsonEncoder). It will convert the f32 to f64 and then transform it into JSON, which may result in inaccurate values. (https://stackoverflow.com/questions/73871891/how-to-serialize-a-struct-containing-f32-using-serde-json)
example: 
f32: 1.1 -> json: 1.100000023841858

**Comment by xiangjinwu** [comment]
It is "right" as defined by IEEE 754 and RFC 8259:
* First, `1.1::float4::float8` in PostgreSQL also produces `1.100000023841858`. It is at the natural of IEEE 754 binary floats.
* But `to_jsonb(1.1::float4)` in PostgreSQL produces `1.1` because it casts to `numeric` rather than `float8`. According to RFC 8259, json number only has good interoperability within IEEE 754 double precision. So it is acceptable to just use `float8` rather than `numeric`. This will not be an issue when we support `numeric` in json as well.

**Comment by xxhZs** [comment]
> It is "right" as defined by IEEE 754 and RFC 8259:
> * First, `1.1::float4::float8` in PostgreSQL also produces `1.100000023841858`. It is at the natural of IEEE 754 binary floats.
> * But `to_jsonb(1.1::float4)` in PostgreSQL produces `1.1` because it casts to `numeric` rather than `float8`. According to RFC 8259, json number only has good interoperability within IEEE 754 double precision. So it is acceptable to just use `float8` rather than `numeric`. This will not be an issue when we support `numeric` in json as well.

The main issue found is in the sink JSON format, where we first convert to JSON and then switch to the type of the target library, which may result in the RW being real1.1 and downstream being f32 1.10000023841858. Is this expected

**Comment by xiangjinwu** [comment]
> which may result in the RW being real1.1 and downstream being f32 1.10000023841858. Is this expected

If the downstream type is also f32, it would be converted back to 1.1 rather than 1.100000023841858.
