### ISSUE TITLE
choose to detect inconsistency in materialized view executor

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14309]
We intend to detect inconsistencies as upstream as possible.

sometimes, the inconsistency error may not originate from the table that produces such an error. The error may occur in the upstream MVs.

When it happens, we can turn this check on and let users recreate all the MVs once to see if we can catch the bug.

**Comment by BugenZhao** [comment]
Do you mean enabling the "dry-run" of conflict handling for materialized views?

https://github.com/risingwavelabs/risingwave/blob/295295d54329cbb33d4e7df2894e31ff96144136/proto/catalog.proto#L321-L326

This sounds like a good point as it reuses the table state of `Materialize` to check the consistency without introducing new states. Some downsides:

- The coverage of cases is limited. Since there are typically `Join` or `Agg` operations in every streaming job, we must also detect (and tolerate) any inconsistencies there first to make it possible for `Materialize` to find them.
- Additional computation and I/O have to be paid on checking. It would be beneficial if we could configure it on the fly, as long as the computation is deterministic and reproducible.
