### ISSUE TITLE
tracking: support change stream subscription

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#14316]
### Is your feature request related to a problem? Please describe.

We observe that users want to subscribe a table or a materialized view directly without kafka in the middle. It's kind of like making RisingWave a message queue (read-only). We need a comprehensive design propsoal for this feature.

**Comment by fuyufjh** [comment]
My major concern is that this might block/back-pressure the streaming task if the consumer is too slow. Any ideas on this?

One possible approach is via log-store. However, this will require a process of creating sink, that is, altering the streaming graph to add a sink with logstore before `subscribe` starts, and removes it after `subscribe` stops. This looks heavy.

**Comment by tabVersion** [comment]
> Instead, I would like to add a CREATE SUBSCRIPTION command.

+1 for both this syntax and using log store for subscription (it is another form of sink I think). 

I am a little confused about what users do with the results, I think what subscription does is print the chunks on the frontend.

**Comment by james-johnston-thumbtack** [comment]
This sounds to me like a RisingWave equivalent to PostgreSQL logical replication.

So some of the basics that you can do with a PG replication slot:
- Create a slot
- Read from the slot, or just peek from it
- Monitor how far you're lagging
- The slot is permanent and lives through reboots of both the client and the RisingWave cluster.
- Drop a slot

Here it can be called a subscription, but fundamentally it seems like the same basic requirements and use cases?

Seems like a useful option if the user doesn't want Kafka as an intermediary, but also there is not yet a direct integration with `CREATE SINK`.... in that case a user can integrate on their end by directly ingesting data from RisingWave with a subscription.

**Comment by hzxa21** [comment]
> our log-store was initially designed for checkpoint. I am not sure if we can use it for subscription as well.

Log store is an internally concept and it has the following properties:
1. It contains a in-memory part and persistent part. If downstream can keep up, not all changes will be continously persisted in the persistent part.
2. The visibility boundary of the persistent part of log store is epoch.
3. Log store is partitioned by vnode and provdes no guarantee on message ordering across vnodes.

To adopt log store for subscription, we can ignore 1 because it is not hard to persist all changes continously but we need to make sure 2 and 3 are acceptable.

**Comment by hzxa21** [comment]
This feature is released in `v1.9`.
