### ISSUE TITLE
Compute node OOM for nexmark queries with nightly-20240108

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#14424]
### Describe the bug

We have a lot of OOM for the daily nexmark performance test pipelines with nightly-20240108.
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2827
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2828
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2829

The memory usage are all like this build https://buildkite.com/risingwave-test/nexmark-benchmark/builds/2827

<img width="1072" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/650ae959-2174-46ec-b1a0-0d58841984d4">

<img width="930" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/35356271/f32e4494-4ec0-4862-b9cb-5cc168f29998">

### The version of RisingWave

nightly-20240108

### Additional context

The new commits in nightly-20240108 https://github.com/risingwavelabs/rw-commits-history?tab=readme-ov-file#nightly-20240108

**Comment by huangjw806** [comment]
The same OOM issue occurred longevity test pipeline.
https://buildkite.com/risingwave-test/longevity-test/builds/894
https://buildkite.com/risingwave-test/longevity-test/builds/895

**Comment by xxchan** [comment]
This can be caused by https://github.com/risingwavelabs/risingwave/pull/14375#discussion_r1444167523 (This is resolved by #14427) + #14220


![image](https://github.com/risingwavelabs/risingwave/assets/37948597/e49298e5-ee42-48c8-9527-1d3f059a7e36)


[1704728569-2024-01-08-15-42-48.auto.heap.collapsed.zip](https://github.com/risingwavelabs/risingwave/files/13869142/1704728569-2024-01-08-15-42-48.auto.heap.collapsed.zip)

**Comment by huangjw806** [comment]
#14375 cherry-picked into release-1.6, should we cherry-pick #14427 and #14220 into release-1.6?

**Comment by cyliu0** [comment]
No OOM for nightly-20240109 daily performance test. So close this one.
