### ISSUE TITLE
discussion: make the `offset_col` from kafka a `bigint` by default

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#14689]
```
dev=> select pg_typeof(offset_col), pg_typeof(partition_col) from tpch limit 1;
     pg_typeof     |     pg_typeof     
-------------------+-------------------
 character varying | character varying
(1 row)
```

> the max offset value is so big (int64) that you won’t ever reach it.

varchar and int64 have different orderings,
therefore I think offset as int64 makes more sense? what else will offset be used other than comparing them

**Comment by TennyZhuang** [comment]
In my original idea, the offset column should be an associated type of Connector, and the planner also should be aware of that.

**Comment by tabVersion** [comment]
Will rollback only for new created tables, planning to leave the existing ones. Is it acceptable? @lmatz

**Comment by lmatz** [comment]
> planning to leave the existing ones

This is for backward compatibility, right? I agree and it seems to be inevitable

**Comment by tabVersion** [comment]
here we come to a point handling `u64` in the kernel. 
I vote for the motivation to make the offset column be `int64` (or other compatible types) rather than sticking to `varchar`. But some connectors use u64 as its offset's datatype, which beyond the range of `i64` supported in the kernel. 

here is something to decide:

* whether continue making the offset column be other types?
  * if yes, we are facing the risk of overflow. But the good news is we've never seen such a big offset and the most used kafka use `i64` as its offset type. Then are we going to impl unsigned datatypes?
  * if no, the code will stay unchanged. We use varchar to store the offset, no risk for overflow but inconvenient when comparing values. 

what do you think @lmatz @fuyufjh @st1page

**Comment by tabVersion** [comment]
then close as not planned
