### ISSUE TITLE
main-cron: integration test (deterministic simulation) - others failed with "agent lost" frequently

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#14707]
<img width="504" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/25862682/84233d4d-263b-43e9-9a36-e67cdb070a3f">

In recent main-cron tests, it always failed with "agent lost" after around 7-9 minutes. This is unlikely to be caused by spot instance preemptions, as the timing is too coincidental. Based on our past experience, it could be an OOM issue.

https://buildkite.com/risingwavelabs/main-cron/builds/1570#018d2cc1-77f1-414e-9db2-9d5f0cf55303

**Comment by BugenZhao** [comment]
Started from some commit between `680a8d59f473d61cc707495bc0198d52623c083d` and `1399fcb736386566a6f3c115d46d22cf54db679e`.

**Comment by fuyufjh** [comment]
Suspicious about 4dde9e6e96baa3b068d79e81fab730734694f910 (https://github.com/risingwavelabs/risingwave/pull/14521)... Can you please take a look? @Little-Wallace

**Comment by fuyufjh** [comment]
It passed the yesterday's test. Is it just a coincidence?

**Comment by fuyufjh** [comment]
Did some experiments, but the failure rate seems to be random to me 😅

I'd like to separate the test into multiple parts: `backfill_tests` `storage` `sink`, so that we can know the failure in a finer granularity. Furthermore, it's easier to assign a true responsible person for any new failures.

https://github.com/risingwavelabs/risingwave/blob/940f1acc1e9da871cb2f6bfa2026bd9c28c67a5e/ci/workflows/main-cron.yml#L266-L268
