### ISSUE TITLE
Pack dashboard resources in release package

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#15280]
> This will actually break the old-version RW, but it's acceptable to me.
>
> This is because RisingWave's Web resources are served from GitHub repo [dashboard-artifact branch](https://github.com/risingwavelabs/risingwave/tree/dashboard-artifact), and it's not versioned, i.e. only the latest main build will be kept. 
>
> https://github.com/risingwavelabs/risingwave/blob/ae7d7ba426818d43209be545ad72f979ce3dacc0/docker/Dockerfile.hdfs#L30-L31
>
> Hope someday we can ship the frontend resource into / along with the binary.

_Originally posted by @fuyufjh in https://github.com/risingwavelabs/risingwave/issues/15277#issuecomment-1965676608_

I think we can take the same approach as the java code, that is, ship the `.jar`s with RisingWave binary together in the `tar.gz` file

**Comment by BugenZhao** [comment]
It appears that `Dockerfile.hdfs` is quite outdated. 😄 We've already switched to build the dashboard artifact in place since #12421.

https://github.com/risingwavelabs/risingwave/blob/5a85fe92beea384b13fbec37296aded23774fc4c/docker/Dockerfile#L15-L25

Specifically for this case, I would strongly suggest maintaining `Dockerfile.hdfs` as an extra **step** in `Dockerfile` to avoid such inconsistencies. 

----

However, the issue still exist if there's no `--dashboard-ui-path` specified. We'll proxy to `githubusercontent.com` then at runtime and it's not versioned. This affect the users who directly download the binary directly or through `Homebrew`.

https://github.com/risingwavelabs/risingwave/blob/5a85fe92beea384b13fbec37296aded23774fc4c/src/meta/src/dashboard/proxy.rs#L76-L79

**Comment by BugenZhao** [comment]
Plan:

- Introduce a new crate `dashboard` to build the dashboard assets in the build script (`build.rs`) conditionally based on the configuration, providing a unified entry for serving dashboard assets.
  * Always build and embed in the binary for releases, requiring `nodejs` toolchain.
  * Do not build but proxy to GitHub for debug/CI builds, unless asked to build.

- The `meta` crate will depends on `dashboard` and be no more aware of the source of the dashboard assets. `ui-path` is deprecated as there's no need of external assets.
