### ISSUE TITLE
consider short-circuit when constant folding

### ISSUE THREAD

**Issue by st1page** [risingwavelabs/risingwave#15724]
```SQL
dev=> create table t(x int);
CREATE_TABLE
dev=> select true OR 'abc'::int > 10;
 ?column?
----------
 t
(1 row)

dev=> select true OR 'abc'::int > x from t;
ERROR:  Failed to run the query

Caused by these errors (recent errors listed first):
  1: Expr error
  2: Parse error: integer invalid digit found in string
```

So for the first expression, RW's optimizer can identify the whole expression as a constant expression and evaluate it when generating the plan, in this case the short-circuit evaluation will take effect.
But for the second expression, the optimizer does not consider it as a whole constant value due to the presence of the variable `x`. But it will identify the `'abc::int'` as a constant expression and evaluate it separately.

**Comment by st1page** [comment]
additional information:
The example looks very strange and can be fixed by modifying the SQL. But in the real case, the SQL is generated by the application.
```SQL
select '${application_varible}' = 'None' OR '${application_varible}'::int > x from t;
```

**Comment by kwannoel** [comment]
As a quick workaround perhaps we can have a `hide` / `unconst` operator which can mask the inner const value to make it seem non-const.

**Comment by kwannoel** [comment]
For now I have suggested using `repeat` to mask the var:
```
repeat('${application_variable}', x * 2 - x);
```

**Comment by chenzl25** [comment]
cc @xzhseh Could you please extend your filter simplify rule to handle this case as well?

**Comment by xzhseh** [comment]
Another workaround maybe - we could add a specific short circuit checker inside `is_const`, this will allow `try_fold_const` to trigger `BinaryShortCircuitExpression::eval_row`, which should correctly handle the case.

We could also handle the short-circuit case during optimization, specially for pattern like `true or (...)` & `false and (...)`, but this approach should carefully maintain the **semantic**.

I have no preference, since the performance will not differ a lot.

**Comment by chenzl25** [comment]
> Another workaround maybe - we could add a specific short circuit checker inside is_const, this will allow try_fold_const to trigger BinaryShortCircuitExpression::eval_row, which should correctly handle the case.
