### ISSUE TITLE
Support `rw_int256` type in Postgres CDC source

### ISSUE THREAD

**Issue by stdrc** [risingwavelabs/risingwave#15977]
### Is your feature request related to a problem? Please describe.

We need to support convert Postgres `numeric` which actually stores an int256 value to our `rw_int256`. Current implementation only allow `decimal` type through `rust_decimal` crate, and the accuracy is not enough for some user cases.

**Comment by lmatz** [comment]
what would be the solution?
1. let users use `varchar` to ingest `numeric` first and then cast to `int256`
2. or allow users to map from `numeric` to `int256` directly

**Comment by bestmike007** [comment]
Thanks @stdrc 

This issue was initially discussed on Slack: https://risingwave-community.slack.com/archives/C03BW71523T/p1711419543170449

It'll be even better if it can be configurable to cast numeric fields into int256/uin256(if you have it in the future)/double/varchar.

**Comment by bestmike007** [comment]
> what would be the solution?

@lmatz I vote for 2, which requires less storage

**Comment by fuyufjh** [comment]
>  int256/uin256(if you have it in the future)/double/varchar.

Agree. We may also support `varchar` and `double` for different use cases.

**Comment by bestmike007** [comment]
And I haven't tested yet, can you sink rw_int256 fields into postgres numeric fields?

**Comment by KeXiangWang** [comment]
Hi @bestmike007. According to our discussion today, I've created a hotfix for your case. The code is in branch [wkx/hotfix-cdc-source-int256](https://github.com/risingwavelabs/risingwave/tree/wkx/hotfix-cdc-source-int256), which is based on the most recently released v1.8. You can get the image with `docker pull ghcr.io/risingwavelabs/risingwave:git-cb2561e7d4ab1cffa8e8f06b510df4e404f4b603`

Here are some notes worth mentioning:
- The implemented solution adapts the second approach [discussed earlier](https://github.com/risingwavelabs/risingwave/issues/15977#issuecomment-2024597361). It requires a simple change when creating a table: modifying the field type from numeric to rw_int256. For example, if the table in pg is `create table local_numeric(id int PRIMARY KEY, num numeric)`, then you should create table in Risingwave with `CREATE TABLE local_numeric (id int,num rw_int256,PRIMARY KEY (id)) WITH ( ...`.
- Currently, this solution is specific to PostgreSQL CDC, resembling a workaround rather than a robust feature, which is why it's not yet PR towards main branch.
- The fix contains a convertion for `decimal` of [rust-postgres](https://github.com/sfackler/rust-postgres) to RW's `rw_int256`. In order to achieve this, I utilized another [repo](https://github.com/tzConnectBerlin/rust-pg_bigdecimal/tree/main) to first convert `pg-decimal` to str and then convert str to `rw_int256`. The repo has not been actively maintained for some time, so this fix may be buggy. I'll continue to look for better solution. 

Please let us know, if there's any further problem meet. 

The issue should be open until we find a good general solution and merged it into main branch.

**Comment by xiangjinwu** [comment]
Additional note: special values `nan`/`inf`/`-inf` may not work properly: #16395
