### ISSUE TITLE
The subscription doesn't appear to be handling the vnode bitmap update correctly.

### ISSUE THREAD

**Issue by shanicky** [risingwavelabs/risingwave#16174]
### Describe the bug

commit d0f8e58739a15ae5529a16551b84bd9cc3ccf78c

```
./risedev p
```

run sql

```
dev=> create table t(v int);
CREATE_TABLE
dev=> create subscription subscription1 from t with (retention = '1D');
CREATE_SUBSCRIPTION
dev=> alter table t set parallelism = 1;
```
It could lead to a panic.

```
2024-04-06T19:06:29.940053+08:00  INFO      rw-main risingwave_meta::barrier::state: update paused state current=Some(ConfigChange) new=None
thread 'rw-streaming' panicked at src/storage/src/hummock/store/local_hummock_storage.rs:451:9:
There is uncommitted staging data in read version table_id TableId { table_id: 3 } instance_id 2 on vnode bitmap update
```

**Comment by hzxa21** [comment]
It is because subscription will write to state store on seeing a barrier even after pause: https://github.com/risingwavelabs/risingwave/blob/436884afdab83d6ba62e6e662ad05ff9a4d72f03/src/stream/src/common/log_store_impl/subscription_log_store.rs#L90

Discussed offline with @xxhZs. It will be fixed in #15180

**Comment by hzxa21** [comment]
We can hotfix it in main/release-1.8 but subscription is an unreleased feature so no user should be using it. So I think it is okay to not block 1.8.1. Is the assertion caught by CI tests?

**Comment by xxhZs** [comment]
test it , fixed
