### ISSUE TITLE
Enable casting jsonb to struct

### ISSUE THREAD

**Issue by erikamundson** [risingwavelabs/risingwave#16268]
### Is your feature request related to a problem? Please describe.

It would be nice to be able to cast jsonb to a defined struct type, similar to [Trino's cast json to ROW](https://trino.io/docs/current/functions/json.html#cast-from-json).

```sql
SELECT CAST(JSON '{"v1":123,"v2":"abc","v3":true}' AS
            ROW(v1 BIGINT, v2 VARCHAR, v3 BOOLEAN));
-- {v1=123, v2=abc, v3=true} 
```

### Describe the solution you'd like

The ability to run a query like this would be very useful for us (especially if it supports json arrays as values within the json object).

```sql
SELECT CAST('{"v1":123,"v2":"abc","v3":true}'::jsonb AS
            struct<v1 BIGINT, v2 VARCHAR, v3 BOOLEAN>);
```

### Describe alternatives you've considered

I haven't found a great alternative within risingwave, we can get the values out like this but it doesn't seem to support json arrays as values within the outer object.
```sql
select 
	fake,
	(fake ->> 'v1', fake->>'v2', fake->>'v3')::struct<v1 BIGINT, v2 VARCHAR, v3 BOOLEAN> as fake_struct
from (
	select '{"v1":123,"v2":"abc","v3":true}'::jsonb as fake
)
```

### Additional context

Currently that desired sql gives this error 

```
SQL Error [XX000]: ERROR: Failed to prepare the statement

Caused by these errors (recent errors listed first):
  1: Failed to bind expression: CAST(CAST('{"v1":123,"v2":"abc","v3":true}' AS JSONB) AS STRUCT<v1 BIGINT, v2 CHARACTER VARYING, v3 BOOLEAN>)
  2: Bind error: cannot cast type "jsonb" to "struct<v1 bigint, v2 character varying, v3 boolean>" in Explicit context
```

**Comment by xiangjinwu** [comment]
In [PostgreSQL](https://www.postgresql.org/docs/current/functions-json.html), conversion from `jsonb` to `struct` (aka `record`/`row`) is supported by 4 functions:
| | with specified field types | with inferred field types |
|-|-|-|
| single record | jsonb_populate_record | jsonb_to_record |
| array of records | jsonb_populate_recordset | jsonb_to_recordset |

So we would prefer to achieve it consistently in the PostgreSQL dialect, rather than cast as in Trino.
There is actually a WIP PR: #13421 by @wangrunji0408 

> it doesn't seem to support json arrays as values within the outer object

The workaround you shared is using `->>` rather than `->`. The former always returns a string, and then cast from string into desired type - assuming the json display format and PostgreSQL display format is the same. This is true for numbers and booleans, but somehow PostgreSQL decides to display arrays with curly braces `{1,2,3}` rather than squared brackets `[1,2,3]` and we followed it. (So a more hacky workaround is to manipulate string and `replace`/`translate` them before casting to array.)

**Comment by erikamundson** [comment]
@xiangjinwu Thanks! The string replace works for now, and it sounds like the `jsonb_populate_record` function is what we're looking for, will follow progress on the linked PR.

**Comment by xiangjinwu** [comment]
Starting from `nightly-20240425` (to be built at noon UTC) the following is available:

```
SELECT jsonb_populate_record(
  null::struct<v1 BIGINT, v2 VARCHAR, v3 BOOLEAN>,
  '{"v1":123,"v2":"abc","v3":true}'::jsonb
);

SELECT
  case when v3 then v1 else length(v2) end
FROM jsonb_populate_record(
  null::struct<v1 BIGINT, v2 VARCHAR, v3 BOOLEAN>,
  '{"v1":123,"v2":"abc","v3":true}'::jsonb
);

SELECT
  t.foo, case when v3 then v1 else length(v2) end
FROM t, jsonb_populate_record(
  null::struct<v1 BIGINT, v2 VARCHAR, v3 BOOLEAN>,
  t.jsonb_column
);
```
