### ISSUE TITLE
Compactor OOM when run nexmark q19,q20 with minio storage

### ISSUE THREAD

**Issue by huangjw806** [risingwavelabs/risingwave#16685]
test setting:
```
KUBEBENCH_CONFIG="{'benchmark':{'risingwave':{'storage':{'type':'minio'}},'minio':{'enabled':true,'node_selector':'risingwave.cloud/nodegroup-name:ondemand-ng-test-8c16g-ssd-0','resources':{'cpu':{'limit':'8','request':'7'},'mem':{'limit':'13Gi','request':'13Gi'}},'persistence':{'enabled':false}}}}"
RW_META_STORE="postgresql"
RW_VERSION="nightly-20240507"
```

**test pipeline:**

https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3648
https://buildkite.com/risingwave-test/nexmark-benchmark/builds/3639

**compactor pod state:**
```
State:          Running
  | Started:      Thu, 09 May 2024 08:54:08 +0000
  | Last State:     Terminated
  | Reason:       OOMKilled
  | Exit Code:    137
  | Started:      Thu, 09 May 2024 08:49:00 +0000
  | Finished:     Thu, 09 May 2024 08:49:04 +0000
  | Ready:          True
  | Restart Count:  7
  | Limits:
  | memory:  4Gi
  | Requests:
  | memory:   2Gi
```

- https://github.com/risingwavelabs/risingwave/issues/15946

**Comment by hzxa21** [comment]
Compactor memory usage is 2x larger in MinIO than in S3. Findings:
1. Object store throughput is higher in MinIO than in S3.
2. Object store rates are similar
3. Object store latency is also higher in MinIO than in S3.

1 and 2 make sense but 3 is surprising. We suspect that 3 is the reason for the OOM because when the slower the upload request, the more buffer will be accumulated in compactor because the uploads are concurrent.

MinIO run:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/6db7790c-a82c-4440-83b2-6ea5ab240301)

![image](https://github.com/risingwavelabs/risingwave/assets/5518566/34859379-28ed-4518-83b5-ec4650e6337a)

S3 run:
![image](https://github.com/risingwavelabs/risingwave/assets/5518566/02ed301d-da12-4310-bb70-bc4d6d5f7ef3)

![image](https://github.com/risingwavelabs/risingwave/assets/5518566/cdf8d546-b58b-4dc9-bc0f-c9272afae9da)

**Comment by hzxa21** [comment]
See https://github.com/risingwavelabs/risingwave/issues/15946#issuecomment-2219975467
