### ISSUE TITLE
Don't let jni_core depends on (the whole) storage crate

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#17177]
.. which makes storage blocking other crates compiling too early.

<img width="676" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/37948597/3304b118-06b8-47b4-aca6-bea8b7a5067e">

**Comment by wenym1** [comment]
> @wenym1 May I ask where is `HummockJavaBindingIterator` used? 🤔

It's used in the RW query engine plugins(spark, trino, ...) that can access object store hummock data directly. It was an experimental feature that has implemented a trivial version but has not published yet. I will try to move some related java native methods to separate crate so that the connector node part does not need to depend on hummock.
