### ISSUE TITLE
v2.1.0-rt.9 needs more time to recover from chaos test

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#19693]
### Describe the bug

<img width="1318" alt="image" src="https://github.com/user-attachments/assets/e4919c8b-53c9-4126-b667-3970f9c1562f">
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/74bce421-6d6c-4366-92b7-a879f760fa28">

It's recovered eventually 2 mins after the queries failed.

https://buildkite.com/risingwave-test/chaos-mesh/builds/1198#019397bd-2418-4e45-8307-e2b42813f94d/20140

https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22kah%22:%7B%22datasource%22:%22edw30bp59yccgb%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22longcmkf-20241205-165435%5C%22,%20container%3D%5C%22meta%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22edw30bp59yccgb%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733417416709%22,%22to%22:%221733426509743%22%7D%7D%7D&orgId=1

### The version of RisingWave

v2.1.0-rt.9

**Comment by lmatz** [comment]
![SCR-20241206-gtt](https://github.com/user-attachments/assets/33174e62-faf3-4b78-93ce-35533d8c69ea)

This is the pod status after the whole experiment of the previous chaos ends

6,3,3,1,10


![SCR-20241206-gux](https://github.com/user-attachments/assets/39cd7343-6a30-419b-af9c-eff58503fbff)

This is the pod status after the current chaos ends (meaning that the chaos has been removed).

6,3,3,2,10

The timestamp of the "Triggering experiment" is at 2:49
The chaos lasted for 600s.

![SCR-20241206-gz6](https://github.com/user-attachments/assets/81ec44d7-d161-460a-82be-56e149d2641e)

And just to be cautious, we waited for another 100s before querying the RW cluster.

![SCR-20241206-h6e](https://github.com/user-attachments/assets/554bb292-aaa4-499f-b2aa-ff3a410f88ee)


During the entire chaos experiment, only the frontend pod restarts once:
https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22kah%22:%7B%22datasource%22:%22edw30bp59yccgb%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22longcmkf-20241205-165435%5C%22,%20pod%3D%5C%22benchmark-risingwave-frontend-f-7d798dcfff-qprdw%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22edw30bp59yccgb%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733424414853%22,%22to%22:%221733425220565%22%7D%7D%7D&orgId=1
![SCR-20241206-h91](https://github.com/user-attachments/assets/02ffa960-8d86-4b18-a4fa-ab27ab1167c9)

**Comment by yezizp2012** [comment]
During recovery, after scaling actors was complete the recovery process was blocked by waiting for stream control reset:
```
2024-12-06 03:05:44.461 | }:recovery_attempt: risingwave_meta::barrier::recovery: control stream reset elapsed=393.147982872s
```
After that, the cluster recovered at 3:05:46. Cc @wenym1 any ideas?

**Comment by hzxa21** [comment]
We just found out the root cause. It is because CN1 is slowly handling the sync error, causing a delay in processing the stream reset. Logs [here](https://grafana.test.risingwave-cloud.xyz/explore?schemaVersion=1&panes=%7B%22kah%22:%7B%22datasource%22:%22edw30bp59yccgb%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22longcmkf-20241205-165435%5C%22,%20pod%3D%5C%22benchmark-risingwave-compute-c-1%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22edw30bp59yccgb%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%221733425081000%22,%22to%22:%221733425564000%22%7D%7D%7D&orgId=1)

The reason why the error handling is slow is because we will wait for 3s when handling each error trying to collect the more actor errors [here](https://github.com/risingwavelabs/risingwave/blob/1add86da1a5deda0a9010f6390af45e994de50ce/src/stream/src/task/barrier_manager.rs#L644). In this case, there are one error per in-flight epoch and given that the actors are all exited, there will be N*3s waiting for sure, causing significant delay.

**Comment by wenym1** [comment]
Closed with https://github.com/risingwavelabs/risingwave/pull/19700

**Comment by lmatz** [comment]
Is the restart of the frontend node related to this error handling change?
