### ISSUE TITLE
discussion: representing DAG in stream plan?

### ISSUE THREAD

**Issue by skyzh** [risingwavelabs/risingwave#2312]
After https://github.com/singularity-data/risingwave/pull/2263 gets merged, we can considering representing the plan as a DAG.

Case 1: Delta Join

The delta join lookup matrix is no doubt a DAG.

Case 2: CTE

The `with` part can be re-used in streaming, instead of creating a new plan tree whenever the with part is used.

In these two cases, we all need to represent the streaming plan as a DAG.

Some considerations:

* Should we directly generate fragments in `to_stream` function?
* Or should we have some kind of intermediate representation of DAG plan?
* Can column pruning, distribution derivation, etc. be applied on DAG plan?
* What should be the output of `explain`?
* ...

Welcome to discuss!

**Comment by liurenjie1024** [comment]
Do you mean DAG in protobuf or in rust `Plan` tree?

**Comment by skyzh** [comment]
Inside Rust.

**Comment by xiangjinwu** [comment]
The logical plan may also need to be a DAG for `with`/CTE, if we do not want to detect duplicated subtree and merge them back.

However, some logical plan optimizer rules may be assuming the plan is a tree, and the same subtree from `with` may be optimized to different plan subtrees.

**Comment by st1page** [comment]
#### use PlanNode to express DAG
because our plan nodes' inputs are represented RC, our PlanNode can express a DAG plan. also, the plan node id can identify the plan node. 
#### not use PlanNode DAG in logical phase
I think the `to_stream` function will give a DAG with `PlanNode`. and on that DAG we can do some specific optimization on stream plan, such as delta join rewrite. although the CTE will generate a DAG, I prefer to treat the common subgraph as different subtrees with the same content. And after `to_stream` we can try to find the same part on that DAG and rewrite it.
- the common subgraph on DAG might prevent some optimizing, such as some predicate push-down
- our batch execution actually doesn't support processing a DAG plan.
#### fragmenter directly process PlanNode DAG
now in #2263 the planNode is converted to post and then fragmented, it is same behavior with meta fregmentor. but after remove fragmenter from meta to frontend, the fregmentor can process the PlanNode tree or DAG directly.
#### new visitor and rewriter for PlanNode DAG
the old `prune_col`, `plan_visitor`, `plan_rewriter` can be used on PlanNode DAG. so we can give a new plan_dag_visitor and plan_dag_rewriter. The plan_dag_visitor will have a Set<PlanNodeId> to store what nodes have been visited. and the plan_dag_rewriter will have a Map<PlanNodeId, PlanNodeRef> to store the nodes have been rewritten

**Comment by BowenXiao1999** [comment]
What may be the most significant efforts to change from `tree` to `DAG`? The traversal algorithm?
