### ISSUE TITLE
Discussion: subquery caused streaming nested-loop join

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#2655]
Currently, TPC-H Q11 and Q22 are not supported in streaming, because their query plans need to introduce nested-loop join operator.

Plan of Q11:

```
    LogicalProject { exprs: [$0, $1] }
      LogicalJoin { type: Inner, on: ($2 > $3) }  <---- NON-EQUI JOIN HERE
        LogicalAgg { group_keys: [0], agg_calls: [sum($1), sum($1)] }
          LogicalProject { exprs: [$0, ($2 * $1)] }
            LogicalJoin { type: Inner, on: ($3 = $4) }
              LogicalProject { exprs: [$0, $2, $3, $5] }
                LogicalJoin { type: Inner, on: ($1 = $4) }
                  LogicalScan { table: partsupp, columns: [ps_partkey, ps_suppkey, ps_availqty, ps_supplycost] }
                  LogicalScan { table: supplier, columns: [s_suppkey, s_nationkey] }
              LogicalProject { exprs: [$0] }
                LogicalFilter { predicate: ($1 = 'ARGENTINA':Varchar) }
                  LogicalScan { table: nation, columns: [n_nationkey, n_name] }
        LogicalProject { exprs: [($0 * 0.0001000000:Decimal)] }
          LogicalAgg { group_keys: [], agg_calls: [sum($0)] }
            LogicalProject { exprs: [($1 * $0)] }
              LogicalJoin { type: Inner, on: ($2 = $3) }
                LogicalProject { exprs: [$1, $2, $4] }
                  LogicalJoin { type: Inner, on: ($0 = $3) }
                    LogicalScan { table: partsupp, columns: [ps_suppkey, ps_availqty, ps_supplycost] }
                    LogicalScan { table: supplier, columns: [s_suppkey, s_nationkey] }
                LogicalProject { exprs: [$0] }
                  LogicalFilter { predicate: ($1 = 'ARGENTINA':Varchar) }
                    LogicalScan { table: nation, columns: [n_nationkey, n_name] }```
```

Plan of Q22:

```
    LogicalAgg { group_keys: [0], agg_calls: [count, sum($1)] }
      LogicalProject { exprs: [Substr($0, 1:Int32, 2:Int32), $1] }
        LogicalJoin { type: Inner, on: ($1 > $2) }  <---- NON-EQUI JOIN HERE
          LogicalProject { exprs: [$1, $2] }
            LogicalJoin { type: LeftAnti, on: ($3 = $0) }
              LogicalFilter { predicate: In(Substr($1, 1:Int32, 2:Int32), '30':Varchar, '24':Varchar, '31':Varchar, '38':Varchar, '25':Varchar, '34':Varchar, '37':Varchar) }
                LogicalScan { table: customer, columns: [c_custkey, c_phone, c_acctbal] }
              LogicalScan { table: orders, columns: [o_custkey] }
          LogicalProject { exprs: [($0 / $1)] }
            LogicalAgg { group_keys: [], agg_calls: [sum($0), count($0)] }
              LogicalProject { exprs: [$1] }
                LogicalFilter { predicate: ($1 > 0.00:Decimal) AND In(Substr($0, 1:Int32, 2:Int32), '30':Varchar, '24':Varchar, '31':Varchar, '38':Varchar, '25':Varchar, '34':Varchar, '37':Varchar) }
                  LogicalScan { table: customer, columns: [c_phone, c_acctbal] }
```

Nested-loop join is very expensive since joining every single row need scanning all rows from the other side. As a result, Flink SQL disallows it, and so do we.

However, an interesting fact is, the non-equi joins in Q11 and Q22 both satisfy that: their inner side are with only 1 row, which is generated by unnesting the aggregation subquery.

Is it possible to solve this case without introducing a full support of streaming nested-loop join?

Related issue: #1855

**Comment by jon-chuang** [comment]
For context: 
tpchQ11: https://blog.birost.com/a?ID=01700-06aff89d-7a50-47e0-9124-24e7d2b63934
tpchq22: https://github.com/apache/impala/blob/master/testdata/workloads/tpch/queries/tpch-q22.test

Some questions (Q11): why are the agg calls duplicated in the plan:  
```
LogicalAgg { group_keys: [0], agg_calls: [sum($1), sum($1)] }
```

I believe the pattern here is a "scalar subquery", so maybe we could detect these and turn into an evaluation of a literal which is then used in a filter.

**Comment by fuyufjh** [comment]
> why are the agg calls duplicated in the plan:
> LogicalAgg { group_keys: [0], agg_calls: [sum($1), sum($1)] }

Interesting. May be a bug. @likg227 Please take a look.

> I believe the pattern here is a "scalar subquery", so maybe we could detect these and turn into an evaluation of a literal which is then used in a filter.

Yes, it is a "scalar subquery". But for streaming query, the result of the scalar subquery could be changed from time to time, so it's not a literal.

**Comment by jon-chuang** [comment]
I believe the right approach may be a sort-merge join/semijoin. 

But this requires a new sort merge join streaming executor.

Can reuse the sort operator and simply implement a merge operator.

This could then possibly handle more than just scalar subquery

**Comment by jon-chuang** [comment]
Here is a simple sketch:
![File_000](https://user-images.githubusercontent.com/9093549/169225100-57c4ca29-93e1-4521-bbc0-fbf433456482.png)

**Comment by fuyufjh** [comment]
> The range executor can service queries of the form "give me all rows with keys in the range x-y"

I love the idea of "Range" operator, but range partition is hard for streaming because you cannot know the data distribution when creating the actors.

**Comment by lmatz** [comment]
> Nested-loop join is very expensive

It seems the meaning of "expensive" here is two-fold in a loose sense:
1. If we execute this query in batch, it is expensive.
2. If we execute this query in streaming, it has some extra cost due to `update amplification`.

I think when a user writes such a SQL (streaming) query, he is expected to bear the first cost although he may not realize it would be slow. And we definitely want to lower the second cost as much as possible, 0 the best.

Since the latest result of the scalar subquery can arbitrarily change, we can delay the execution of the last non-equal join(or the subquery should not output its scalar result to the non-equal join executor) until we believe we really have to execute it, otherwise a new snapshot of MV will miss the deadline, i.e. the user's MV freshness requirement. But for the rest of the executors, they probably should execute as soon as their receive any input. Although an insertion and a deletion of the same PK would very likely lead to waste of computation, eager execution leads to more benefits than the cost for the rest executors as their computation is so cheap.

This is a naive solution, i.e. some executors execute lazily, to make Jon's `|updates| << |total state|` as `<<` as possible.

Which subset of executors should execute eagerly and which subset should execute lazily, or switch between two modes, to have a good tradeoff between freshness, cost, and performance? 
Maybe we can formulate the problem for general queries/cases and see whether it is trivial to answer or worth further consideration.

**Comment by jon-chuang** [comment]
Btw, regarding this issue:
Some questions (Q11): why are the agg calls duplicated in the plan:

```
LogicalAgg { group_keys: [0], agg_calls: [sum($1), sum($1)] }
```

Its not yet solved, and I seem to encounter it again on:
 
 ```
- sql: |
    create table product(p_id int, price int);
    create table user(user_id int, budget int);
    select * from user, lateral (select * from product where price = budget);
  optimized_logical_plan: |
    LogicalJoin { type: Inner, on: ($4 = $1), output_indices: [0, 1, 2, 3] }
      LogicalScan { table: user, columns: [user_id, budget] }
      LogicalProject { exprs: [$0, $1, $1] }
        LogicalScan { table: product, columns: [p_id, price] }
```

Take note the duplicated expr: `LogicalProject { exprs: [$0, $1, $1] }`. Maybe we need a dedup expr rule somewhere? It could be complicated as parent nodes may depend on one of the inputs, we need to rewrite all of that recursively. It would be better if duplicated expressions cannot be created in the first place? @xiangjinwu

**Comment by xiangjinwu** [comment]
Talking about duplicated exprs and agg calls (**off topic of this issue**)

This is Q11:
```
select
        ps_partkey,
        sum(ps_supplycost * ps_availqty) as value
from
        partsupp,
        supplier,
        nation
where
        ps_suppkey = s_suppkey
        and s_nationkey = n_nationkey
        and n_name = 'ARGENTINA'
group by
        ps_partkey
having
        sum(ps_supplycost * ps_availqty) > (
                select
                        sum(ps_supplycost * ps_availqty) * 0.0001000000
                from
                        partsupp,
                        supplier,
                        nation
                where
                        ps_suppkey = s_suppkey
                        and s_nationkey = n_nationkey
                        and n_name = 'ARGENTINA'
        )
order by
        value desc;
```
As you can see, the query contains 3 repeated `sum(ps_supplycost * ps_availqty)`: 1 in subquery, 1 in outer having, and 1 in outer select list. So it is not a bug that we generated duplicates, but we do not try hard to dedup user input.

As for the new example involving `lateral`, it looks like the duplication is from our binder/planner/optimizer rather than from user input.

Talking about the solution(s):
* Investigate where the duplicates originated from
* @st1page recently introduced a LogicalProjectBuilder that dedup exprs
* Rewriting indices recursively is already happening during `prune_col`

Again, there are duplicates that cannot be avoided, for example top level duplicates from user input:
```
select a + b, a + b from t;

Option 1: current
     LogicalProject { exprs: [$0 + $1, $0 + $1] }
       LogicalScan { table: t, columns: [a, b] }

Option 2: avoid duplicated addition calculation
     LogicalProject { exprs: [$0, $0] }
       LogicalProject { exprs: [$0 + $1] }
         LogicalScan { table: t, columns: [a, b] }
```
