### ISSUE TITLE
optimize unnest function

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4032]
The values array in List[int8] format is almost the same as that one in int8, except the null value.

If there is no NULL value in the null bitmap, we can extract the value array directly to implement the unnest.

https://github.com/singularity-data/risingwave/blob/8b18f7b367f43ed1332692e3fec5545b70aa8c99/src/common/src/array/list_array.rs#L352-L364

**Comment by TennyZhuang** [comment]
It's proposed by me, but I think it's non-trivial under the current row-based table function framework, so remove the "good-first-issue" now.

**Comment by Graphcalibur** [comment]
I'm interested in taking on this issue but I'm unsure on what exactly needs to be done since currently `ListRef` doesn't have a value array or a null bitmap. Does it need to be converted to [this arrow implementation](https://jorisvandenbossche.github.io/arrow-docs-preview/html-option-4-sidebar-with-dropdown/format/Columnar.html)?
