### ISSUE TITLE
connector: eliminate usages of `RwError`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#4105]

**Comment by tabVersion** [comment]
I think https://github.com/singularity-data/risingwave/pull/3781 has done enough, we can close the issue.

**Comment by BugenZhao** [comment]
> I think https://github.com/singularity-data/risingwave/pull/3781 has done enough, we can close the issue. 

I think this is to be resolved by #4615, not #3781? 👀

**Comment by tabVersion** [comment]
My mistake. the issue is to remove RwError and related result type

**Comment by fuyufjh** [comment]
I just processed a case that every invalid input rows throws an error **with full stack trace** in logs 😇 (Because RwError will capture the Stack)

<img width="1397" alt="image" src="https://github.com/risingwavelabs/risingwave/assets/10192522/6fb35a2c-f8d3-465e-8895-07e7a47e6373">

We need refactor this.

**Comment by fuyufjh** [comment]
@tabVersion It seems that @cnissnzg is not working on this issue? Can you please take it over

**Comment by BugenZhao** [comment]
May wait for the discussion in #11443 for the refactor plan.

**Comment by BugenZhao** [comment]
Resolved by #14950 and following PRs.
