### ISSUE TITLE
storage: No compaction triggered on an imbalanced LSM tree when the cluster is idle

### ISSUE THREAD

**Issue by hzxa21** [risingwavelabs/risingwave#4379]
**Describe the bug**
When the cluster is idle (i.e. source is stopped), we will not trigger compaction on an imbalanced LSM tree after compactor recovers.

This happens when I stopped source and restart compactor node in #4365.

**To Reproduce**
Follow steps in #4365, stop sources and then restart compactor node.

**Expected behavior**
Compaction should be triggered on compactor recovery

**Additional context**
My guess on the root cause is currently we only trigger compaction on `commit_epoch` with non-empty checkpoint and `report_compaction_task`. If the cluster is idle, on compactor failover, `report_compaction_task` will not be called and all checkpoints are empty so compaction will be triggered.

**Comment by Li0k** [comment]
#### some inslight
now `compactor_scheduler` trigger by `try_send_compaction_request`, and `try_send_compaction_request` will be called in two case
- commit_epoch
- report_compact_task

when compactor failover, the state of compact_task (which under processing) will be be lost, so it never call `try_send_compaction_request`.  While in  `commit_epoch` function,  `try_send_compaction_request` only called when data change. Hence, the compact can no longer be triggered   
```rust
  // commit_epoch may contains SSTs from any compaction group
  for id in modified_compaction_groups {
       self.try_send_compaction_request(id);
  }
```

IMHO, it can be solved with issue https://github.com/singularity-data/risingwave/issues/3677. some simple descriptions are as follows

1. Cancellable compact_task by heartbeat 
2. Re-Scheduler compactor by resource occupancy

**Comment by jon-chuang** [comment]
Hi @Li0k 

> Re-Schedule compactor by resource occupancy

I guess if we detect task failure, we should try to reschedule for the failed compaction group.

We should also try to schedule new compaction tasks whenever we add new compactor or restart compactors.

**Comment by jon-chuang** [comment]
> My guess on the root cause is currently we only trigger compaction on commit_epoch with non-empty checkpoint and report_compaction_task.

Actually, if you look in the logic of `CompactionScheduler::pick_and_asign`, technically, every single compaction group for which an epoch was commited would always be in queue. 

That's because `send_task loop will run until `assign_compaction_task` is successful. In which case, we always put the compaction group back onto the queue via `request_channel.try_send(compaction_group);`

So its actually completely inexplicable why compaction is not triggered after sources are stopped and compactor is restarted. The compaction group is actually forever in queue. Whether this behaviour is desired or not is another question.

**Comment by jon-chuang** [comment]
> IMHO, it can be solved with issue https://github.com/singularity-data/risingwave/issues/3677.

After further thought I agree with this completely.

Analysis:
1. If new writes, we always schedule group.
2. If fail, we always reschedule group. If succeed, we always reschedule group.

As long as every incomplete task ends up reliably in heartbeats table, we will eventually reschedule the group.

In particular, we need to ensure that `report_compact_task` is reliable. In particular, if `report_compact_task` fails with error, then we are not guaranteed to always schedule compaction tasks until tree is balanced. Hence, we should always retry `report_compact_task` in a loop until it succeeds, or if we exceed retry count, we need to have a very big, visible error as this should never happen and something needs to be fixed.

However, as long as `report_compact_task` is reliable (including `tx.try_send` which ought to propagate error outwards to `try_send_compaction_request` to return `Result<bool>` rather than just `bool`), we will always eventually arrive at a steady state, wherein if there are no new writes, we have a balanced LSM tree (no new tasks).
