### ISSUE TITLE
Cannot drop database

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4650]
**Describe the bug**

**To Reproduce**
```
dev=> create database db;
CREATE_DATABASE
dev=> drop database db;
ERROR:  QueryError: Catalog error: cannot drop database db because schema public depend on it.
```

**Expected behavior**

**Additional context**

**Comment by xxchan** [comment]
https://github.com/singularity-data/risingwave/blob/2130124f126d1f959c868e0f388932d7cfa3b11b/e2e_test/ddl/database.slt#L17-L31

We have to drop all schemas before droping the db. Is this expected? 😢 (PG can drop db freely)

**Comment by BugenZhao** [comment]
There'll be a lot of ignored error of dropping database when running parallel e2e. 😢

```
All test cases finished in 27965 ms
--
  | + DROP DATABASE ad_ctr_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database ad_ctr_slt because schema public depend on it
  | + DROP DATABASE append_only_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database append_only_slt because schema pg_catalog depend on it
  | + DROP DATABASE basic_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database basic_slt because schema pg_catalog depend on it
  | + DROP DATABASE count_star_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database count_star_slt because schema public depend on it
  | + DROP DATABASE datagen_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database datagen_slt because schema public depend on it
  | + DROP DATABASE ecommerce_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database ecommerce_slt because schema public depend on it
  | + DROP DATABASE extreme_null_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database extreme_null_slt because schema pg_catalog depend on it
  | + DROP DATABASE index_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database index_slt because schema pg_catalog depend on it
  | + DROP DATABASE join_3way_slt;
  | ignore error: db error: ERROR: QueryError: Catalog error: cannot drop database join_3way_slt because schema pg_catalog depend on it
```

cc @yezizp2012 @HuaHuaY Could you please help to take a look? ❤️

**Comment by HuaHuaY** [comment]
> https://github.com/singularity-data/risingwave/blob/2130124f126d1f959c868e0f388932d7cfa3b11b/e2e_test/ddl/database.slt#L17-L31
> 
> We have to drop all schemas before droping the db. Is this expected? 😢 (PG can drop db freely)

It's expected now. May be modified in the future.

**Comment by yezizp2012** [comment]
Currently to drop database requires dropping all exist schemas except `pg_catalog`(the error msg is not well handled as we can see in the logs Cc @HuaHuaY ). This's not compatible with PostgreSQL. I'm not sure whether we should follow pg's behavior or not. Because this's much more complicated in risingwave, we should drop all tables/sources under every schemas recursively in current implementation(drop catalog, inject ddl barrier etc), I'm afraid we might have some inconsistencies if some of the drop operations fails.

Well, I think we might need some batch interfaces for both catalog and barrier command: 1. drop database support batch drop tables/sources/schemas recursively in a transactional interface; 2. support barrier command with multi tables 3. support batch drop sources in CN. Besides, we still need some other mechanism to clean dirty data, mainly the `TableFragments` if table already dropped in catalog. Cc @HuaHuaY

**Comment by xiangjinwu** [comment]
> I'm afraid we might have some inconsistencies if some of the drop operations fails.

What if we rename the database to make its name available first, and then drop the related resources in the background asynchronously?
