### ISSUE TITLE
Duplicated but unambiguous ORDER BY is rejected

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#4977]
### Describe the bug

```sql
create table t (x int);
select x,x from t order by x;
ERROR:  QueryError: Bind error: ORDER BY "x" is ambiguous
```

### Expected behavior

In PG:
```sql
select x,x from t order by x;
 x | x
---+---
(0 rows)
```

### Additional context

However, I think the behavior in risingwave is also acceptable, so feel free to close as won't fix. 😄

**Comment by xiangjinwu** [comment]
The definition of `unambiguous` in PostgreSQL can be tricky:
```
-- same expression is okay
select 1+1+1 as x, 1+1+1 as x order by x;

-- "same" expression with different syntax is okay
select 1+cast(1 as smallint)+1 as x, 1+1::smallint+1 as x order by x;

-- `unknown` is casted before checking equivalence
select 1+1+1 as x, 1+'1'+1 as x order by x;

-- this is not okay
select 1+1::bigint+1 as x, 1+'1'::bigint+1 as x order by x;
```

Given that our focus is on materialized views, where such unambiguous duplications are still disallowed, we may not need to improve usability on such rarely used batch-only thing with complicated logic.

Keeping this issue for some time so that people can provide its necessity or simpler implementation.
