### ISSUE TITLE
pgwire: Support prepared statement

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#5293]
### Is your feature request related to a problem? Please describe.

```javascript
        const res = await conn.query({
          text: 'SELECT $1::int AS number',
          values: ['1'],
        });
```

This is a javascript code that queries to RisingWave with a special `$1` that should be replaced by the parameter '1'. RisingWave currently does not support this feature.

```bash
cd src/utils/pgwire/tests/js
npm i jest -g
jest build/test/pgwire
```

### Describe the solution you'd like

It needs some modification to the pgwire module.

### Additional context

#3676

**Comment by ZENOTME** [comment]
According investigating: 

Client query using prepare statement have three format:
1. without generic param (e.g. select * from table )
2. with generic param and explicit type list, e.g. 
```
//in rust-postgres
client.query_typed('select * from table where id = $1',&[Type::INT])
```
3. with generic param and implicit type, e.g.
```
        const res = await conn.query({
          text: 'SELECT $1::int AS number',
          values: ['1'],
        });
```
NOTE: If the prepare statement with generic param but without explicit type or implicit type, we just assume generic param is VARCHAR.

I prepare to implement this in 2 PR because the code may be too big for just one PR.
1. implement format 1 and 2 
2. implement format 3

**Comment by BowenXiao1999** [comment]
Should closed via #5485

**Comment by ZENOTME** [comment]
It still can't support for some unknown reason... I'm debuging it.

**Comment by ZENOTME** [comment]
I think we can close it now. We can support all prepare statements now.

**Comment by BowenXiao1999** [comment]
We are expected to use prepared statement in TPC-H/sysbench now, but I suspect there are some improvements (I think only save some parsing time?). cc @liurenjie1024 @chenzl25

**Comment by chenzl25** [comment]
> We are expected to use prepared statement in TPC-H/sysbench now, but I suspect there are some improvements (I think only save some parsing time?). cc @liurenjie1024 @chenzl25

For sysbench I think yes, prepare statement can save parsing time or even more aggressively to prepare a plan cache to save optimizer time.
