### ISSUE TITLE
Discussion: Keeps only the all-in-one binary 

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#5326]
It seems not beneficial to keep the separated binary for all components: compute-node, meta-node, compactor, frontend-node ...

Advantage of all-in-one binary:

- ~~Faster to compile~~
   - (Well, as pointed out by @skyzh, single-thread LTO dominates the compiling time)
- Easy for users to deploy

**Comment by skyzh** [comment]
No, it's slower to compile 🥵

The most time-consuming part of compiling all-in-one binary is link-time optimization. Some LLVM passes can only be done in single-thread, and therefore making all-in-one binary slow to compile. In risedev, we keep the convention that we compile compactor/frontend/compute/meta node, so that they will be linked in different threads and make use of all cores.

In debug mode, producing different binaries for each node should be 5-10s faster than all-in-one binary. In release mode, it should be like 1m-2m.

**Comment by skyzh** [comment]
But for deployment, I agree that one binary is good for all.

**Comment by fuyufjh** [comment]
Actually, we do use all-in-one binary for cloud deployment.

However, it seems that there isn't any benefit from removing non-all-in-one compiling target...
