### ISSUE TITLE
feat(frontend): support search path for binder and other functions like current_schemas

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#5447]
### Is your feature request related to a problem? Please describe.

Currently when binding any relations in frontend, binder will only search under `public` schema if user don't specified. But for postgreSQL, `pg_catalog` will be also took into consideration and user can also set search path in session as follows:

```sql
CREATE SCHEMA collate_tests;
SET search_path = collate_tests;
```

Besides, to integrate with other tools like pgcli, which will send some internal queries that don't specify `pg_catalog`, we might need to support search path in `Binder`.

Cc @xiangjinwu @HuaHuaY

**Comment by xiangjinwu** [comment]
For full support, refer to pgdoc ([5.9.3](https://www.postgresql.org/docs/14/ddl-schemas.html#DDL-SCHEMAS-PATH) [5.9.5](https://www.postgresql.org/docs/14/ddl-schemas.html#DDL-SCHEMAS-CATALOG) [var](https://www.postgresql.org/docs/14/runtime-config-client.html#GUC-SEARCH-PATH)).

Alternatively, we could also [reserve names](https://www.postgresql.org/docs/14/ddl-schemas.html#DDL-SCHEMAS-CATALOG:~:text=Since%20system%20table%20names%20begin%20with%20pg_%2C%20it%20is%20best%20to%20avoid%20such%20names) starting with `pg_` and always consider them part of `pg_catalog`. This might be simpler and also follows PostgreSQL's suggestions.
