### ISSUE TITLE
Support scaling of `Sink`

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#5856]
Typically this should be trivial and covered in #5740 as the `Sink` is an alternative to `Materialize`. But do we also need to manage and reassign the "splits" for scaled sink nodes?

Any insights are welcome. 😄 cc @tabVersion @shanicky @nanderstabel

**Comment by tabVersion** [comment]
I think we do not need to do that. Actually, we write data to kafka without specifying a specific partition of the topic. 

To some extent, we should see the sink module as a suffix for the mv operator. In my design, the sink operator should scale out and in together with the upstream. I want to ensure that each sink operator receives no data intersection, so that we can avoid as many as possible conflicts when writing to the downstream, which is now secured by keeping the sink and mv operators at the same parallelism level

**Comment by BugenZhao** [comment]
> In my design, the sink operator should scale out and in together with the upstream.

Great. This assumption is held naturally under the current scheduling strategy.

**Comment by tabVersion** [comment]
@BugenZhao any updates? Now we are  working on remote sink, may check the design with @KivenChen

**Comment by BugenZhao** [comment]
No update yet.

**Comment by BugenZhao** [comment]
I've tested scaling the `Console` sink, and it seems that the meta part works very well, which acts the same as scaling an MV on MV in #5740. However, we don't have sufficient e2e tests for the correctness of `Sink` itself or the scaling of `Sink`.

**Comment by fuyufjh** [comment]
> I've tested scaling the `Console` sink, and it seems that the meta part works very well, which acts the same as scaling an MV on MV in #5740. However, we don't have sufficient e2e tests for the correctness of `Sink` itself or the scaling of `Sink`.

Sounds like the next step is to add more test cases?
