### ISSUE TITLE
Bug: dynamic filter inner side requires exactly one row instead of max one row

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#5860]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/fbd5fd2f4e44032d69ab9d28c72ed34530e1cbfd/src/frontend/src/optimizer/plan_node/logical_join.rs#L1045-L1048

Currently, we use `MaxOneRowVisitor` to restrict dynamic filter inner side, however, what we need should be `ExactOneRowVisitor`, because zero row from inner side means it need to filter out all rows from outer side which is inefficient and should be forbidden.

**Comment by BugenZhao** [comment]
Related: #5773

In streaming, the `SimpleAgg` yields 0 rows, if there's no input or all input has been retracted (#4954). So I'm afraid we'll break all use cases of the dynamic filter if we ensure "exactly one row", including tpch q11 and q22.

Besides, note that we use two ops to represent an update (`(Update)[Insert|Delete]`), there's no guarantee that the `Delete` and `Insert` records received by the dynamic filter are in the same epoch (for example, nexmark q7). So it's quite possible that we need to handle an intermediate state of the inner side having no row.

A simple is to treat no row as `NULL` and yield no rows instead of filtering out all rows. In oracle:
> If the subquery returns 0 rows, then the value of the scalar subquery expression is NULL.

**Comment by chenzl25** [comment]
Currently we accept empty row of inner side of dynamic filter and treat it as NULL which results in deleting all rows of outer side.
