### ISSUE TITLE
storage/streaming: estimate number of records in a table

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#6074]
This statistic will be useful in several cases.

- Optimizer: helps to give a better plan, for example, index selection and join reorder.
- Streaming: estimates the process of creating a materialized view atop a large amount of historical data, #2691

**Comment by hzxa21** [comment]
Will size estimation be more helpful? Here is what I thought:

1. For cardinality estimation (i.e. estimate number of rows of a table), there are two ways to maintain it:
    a. Maintain a internal MV to count the number of rows in a MV table. This is the accurate count. 
    b. Storage maintain the number of keys per table in meta. This is just an appoximation because we can have multiple versions of a single key.
2. For size estimation, we can maintain it like 1b.

@zwang28 and I chatted about adding more granular per-table/mv metric. This can be a good starting point.

**Comment by chenzl25** [comment]
From user perspective, storage estimation how many physical rows (insert and delete) for a table and average of row size is exactly what they need, because they care about the actual size of this materialized view (including internal tables).

For optimizer, both physical row count and logical row count are useful. logical row count can be use to estimates how many rows will produce by the table scan while physical row count can be used to estimate the actual IO of the table scan. 

So I think we can just maintain physical row count of a table/mv in meta as @hzxa21  said.

**Comment by zwang28** [comment]
[Physical row count/size per table](https://github.com/risingwavelabs/risingwave/blob/2235e84a2dbcf14f8360f4eb8089bdc9fab7c7f9/src/meta/src/hummock/manager/versioning.rs#L172) has been available in meta.

Do we still want stats of logical row count for optimizer now?
> Maintain a internal MV to count the number of rows in a MV table

**Comment by BugenZhao** [comment]
> [Physical row count/size per table](https://github.com/risingwavelabs/risingwave/blob/2235e84a2dbcf14f8360f4eb8089bdc9fab7c7f9/src/meta/src/hummock/manager/versioning.rs#L172) has been available in meta.

Good to hear that! Is there an interface for the upper layer to get that?

**Comment by zwang28** [comment]
> Is there an interface for the upper layer to get that
In meta node it's accessible via `HummockManager::get_version_stats`.
Do you mean exposing it to frontend node?

**Comment by BugenZhao** [comment]
Not that urgent. Let's wait until we have a specific need. 🚀

**Comment by zwang28** [comment]
- Physical row count/size per table has been supported.
- Logical row count supporting is not planned.

Please reopen this issue as needed.
