### ISSUE TITLE
According to the Sysbench benchmark, prepare statements perform worse than non-prepare statements so much

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#6163]
### Describe the bug

Prepare statement performance is almost 1000 times worse than non-prepare statement. Need investigation.

### To Reproduce

# prepare statement:

```
sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-bbef335 (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 3s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 16 tps: 6.99 qps: 6.99 (r/w/o: 6.99/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 16 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 16 tps: 1.00 qps: 1.00 (r/w/o: 1.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 7s ] thds: 16 tps: 3.99 qps: 3.99 (r/w/o: 3.99/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 16 tps: 2.00 qps: 2.00 (r/w/o: 2.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 9s ] thds: 16 tps: 2.00 qps: 2.00 (r/w/o: 2.00/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
```

# disable prepare statement:

```shell
 sysbench \
--db-driver=pgsql \
--pgsql-host=localhost  \
--pgsql-port=4566  \
--pgsql-user=root \
--pgsql-db=dev \
--threads=16 \
--report-interval=1 \
--events=0 \
--time=100 \
--percentile=99 \
--auto_inc=false \
--table_size=100000 \
--db-ps-mode=disable \
--skip_trx=true \
--range_size=1 \
/usr/local/share/sysbench/oltp_point_select.lua \
run
sysbench 1.1.0-bbef335 (using system LuaJIT 2.1.0-beta3)

Running the test with following options:
Number of threads: 16
Report intermediate results every 1 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 1s ] thds: 16 tps: 2996.46 qps: 2996.46 (r/w/o: 2996.46/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 2s ] thds: 16 tps: 2994.13 qps: 2994.13 (r/w/o: 2994.13/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 3s ] thds: 16 tps: 2827.23 qps: 2827.23 (r/w/o: 2827.23/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 4s ] thds: 16 tps: 2830.63 qps: 2830.63 (r/w/o: 2830.63/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 5s ] thds: 16 tps: 2930.31 qps: 2930.31 (r/w/o: 2930.31/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 6s ] thds: 16 tps: 2974.51 qps: 2974.51 (r/w/o: 2974.51/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 7s ] thds: 16 tps: 2849.87 qps: 2849.87 (r/w/o: 2849.87/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 8s ] thds: 16 tps: 2903.19 qps: 2903.19 (r/w/o: 2903.19/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 9s ] thds: 16 tps: 2773.98 qps: 2773.98 (r/w/o: 2773.98/0.00/0.00) lat (ms,99%): 0.00 err/s: 0.00 reconn/s: 0.00
```

**Comment by liurenjie1024** [comment]
We've supported prepared statement?

**Comment by chenzl25** [comment]
> We've supported prepared statement?

Yes, https://github.com/risingwavelabs/risingwave/pull/5485
cc @ZENOTME

**Comment by BugenZhao** [comment]
Though it's not the bottleneck for this case, I think we can use a pre-compiled regex with `LazyLock` here.

https://github.com/risingwavelabs/risingwave/blob/891b47d1ede731c4f57ddca0403ed6e4f84b6f5f/src/utils/pgwire/src/pg_extended.rs#L263-L264

**Comment by ZENOTME** [comment]
I will take a investigate

**Comment by ZENOTME** [comment]
## Summary this bug
When enable prepared statement, sysbench will send the prepared statement like this:
`sql: 'SELECT c FROM sbtest1 WHERE id= ?'  param type: [BIGINT]`
Finally our extended protocol will convert the sql into` SELECT c FROM sbtest1 WHERE id= xx::BIGINT`, e.g. ` SELECT c FROM sbtest1 WHERE id= 151::BIGINT `

When we use `SELECT c FROM sbtest1 WHERE id= 151::BIGINT` instead of `SELECT c FROM sbtest1 WHERE id= 151`, the physical query plan is different, and that's why the performance is so bad.

```
SELECT c FROM sbtest1 WHERE id= 151::BIGINT
BatchExchange { order: [], dist: Single }
└─BatchProject { exprs: [sbtest1.c] }
  └─BatchFilter { predicate: (sbtest1.id = 151:Int32::Int64) }
    └─BatchScan { table: sbtest1, columns: [c, id] }

SELECT c FROM sbtest1 WHERE id= 151
BatchExchange { order: [], dist: Single }
└─BatchScan { table: sbtest1, columns: [c], scan_ranges: [id = Int32(151)] }
```
#### Why plan different
For the `WHERE id=<literal>`, we will convert it to scan_ranges in normal cases. But we will make sure 'literal' can be cast implicitly into the type of id before converting it. https://github.com/risingwavelabs/risingwave/blob/568f11bc99aa81b3df659445bcba6f798ff5dfa7/src/frontend/src/utils/condition.rs#L383
So when we use `WHERE id=xxx::BIGINT` and id is int type, it can't be converted to a scan_ranges.

## How to fix it

I think we don't need add '::BIGINT' in extended protocol. Such as in this case, we can convert the sql into ` SELECT c FROM sbtest1 WHERE id= xx`. Because in the bind phase, it will assign a appropriate type for number literal.https://github.com/risingwavelabs/risingwave/blob/568f11bc99aa81b3df659445bcba6f798ff5dfa7/src/frontend/src/binder/expr/value.rs#L53

**Comment by BowenXiao1999** [comment]
So int can not be implicitly cast to BIGINT? Is this expected? I think there is no overflow.
cc @xiangjinwu

**Comment by ZENOTME** [comment]
> So INT can not be implicitly cast to BIGINT?

In this case, we try to cast BIGINT implicitly to INT.
`SELECT c FROM sbtest1 WHERE id= xx::BIGINT`, the literal 'xx::BIGINT' is BIGINT, and id is INT.

I think INT can be cast implicitly to BIGINT.

**Comment by BowenXiao1999** [comment]
Cool. So let's close this issue via that PR
