### ISSUE TITLE
bug: hummock event handler panicked at unwrap

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#6218]
### Describe the bug

```
{
    "log": "thread 'risingwave-main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /risingwave/src/storage/src/hummock/event_handler/hummock_event_handler.rs:332:27\n",
    "stream": "stderr",
    "kubernetes": {
        "pod_name": "risingwave-compute-0",
        "namespace_name": "rwc-3-longevity-20221106-100331",
        "pod_id": "e5a9c776-6e5e-4b4d-929a-f0cdb77fe523",
        "host": "ip-10-0-1-44.ap-southeast-1.compute.internal",
        "container_name": "compute",
        "docker_id": "dc7b24b07326da537d2d78e422a5aaeca8c9fa08fd0a83c765f23a53372ce3ee",
        "container_hash": "ghcr.io/risingwavelabs/risingwave@sha256:bfbea25369de976db9fc6205a7d40c26d513faa21119f89911b3474381c46a8c",
        "container_image": "ghcr.io/risingwavelabs/risingwave:latest"
    }
}
```

Logs can be found here:

https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Frls-apse1-eks-a$252Fapplication/log-events/ip-10-0-1-44.ap-southeast-1.compute.internal-application.var.log.containers.risingwave-compute-0_rwc-3-longevity-20221106-100331_compute-dc7b24b07326da537d2d78e422a5aaeca8c9fa08fd0a83c765f23a53372ce3ee.log$3FfilterPattern$3Dpanicked

https://ap-southeast-1.console.aws.amazon.com/cloudwatch/home?region=ap-southeast-1#logsV2:log-groups/log-group/$252Faws$252Fcontainerinsights$252Frls-apse1-eks-a$252Fapplication/log-events/ip-10-0-3-81.ap-southeast-1.compute.internal-application.var.log.containers.risingwave-compute-2_rwc-3-longevity-20221106-100331_compute-c2103001b3dbbcc51388cd5eaac01ee71861b207ebf7b169c111697184a2d5b2.log$3FfilterPattern$3Dpanicked

### Additional context

Maybe related? #6200

**Comment by wenym1** [comment]
It seems not related to #6200. 

The panic is caused during CN handling a `force_stop_actors` RPC. The RPC handle sends a `Clear` event, and wait on a oneshot rx on completion. After handling the `Clear` event, the event handler will `tx.send` to notify the completion.

Our current `tx.send` uses an `unwrap`, which is the cause of this panic. We can fix it by removing the `unwrap` and report a log instead. But it's strange that the `tx.send` will fail, because it means that the rx is dropped, which means the handle for `force_stop_actors` RPC is dropped.
