### ISSUE TITLE
DynamicFilter does not fetch the new range after the vnode map is updated 

### ISSUE THREAD

**Issue by shanicky** [risingwavelabs/risingwave#6414]
### Describe the bug

In the latest Commit, `DynamicFilter` does not seem to be handling the state data correctly after the `vnode_bitmap` update

It only fetches the data of the updated vnodes if the range has changed, but not if the new range is within the existing range, which is fine under normal circumstances.

But in the case of scaling, if the `vnode_bitmap` is updated by scaling, if the new range is within the existing range, no `missing_ranges` will be generated and the data corresponding to the updated vnodes will not be fetched, which will lead 
to data loss.

PR #6415 attempts to forcibly clear the currently held range [here](https://github.com/risingwavelabs/risingwave/blob/3c4a8cdd43efe6c5fe06b3738e0207315cac207c/src/stream/src/executor/managed_state/dynamic_filter.rs#L200), and clears the cache at [here](https://github.com/risingwavelabs/risingwave/blob/3c4a8cdd43efe6c5fe06b3738e0207315cac207c/src/stream/src/executor/managed_state/dynamic_filter.rs#L139), thus triggering a forced data pull, but I'm not sure if this will cause performance issues here (after all, scaling are not usually happened)

cc @BugenZhao

**Comment by jon-chuang** [comment]
Indeed, it seems that we should not reset the range to `None`. 

If the new vnode set is contained in the previous (typical case - scaling up), we are ok to just evict, and retain the current range. If the vnode set is not contained (scaling down), then since this is the atypical case, we could just reset the entire cache and force a pull. Or, we can cause the fetch during update_vnode_bitmap.

I will go with the former solution for now.

**Comment by jon-chuang** [comment]
Actually, it seems like sort operator will fetch the new ranges upon scaling. Not sure if we want to do the same. But it should be easy to do so... https://github.com/risingwavelabs/risingwave/pull/6377/files

**Comment by soundOfDestiny** [comment]
fixed in #6462
