### ISSUE TITLE
timestamptz error info and pg compatibility issues

### ISSUE THREAD

**Issue by cyliu0** [risingwavelabs/risingwave#6431]
### Describe the bug

Now we have 2 problems about the timestamptz feature in 0.1.14-rc.

1. The error info about timestamptz column format is not correct. `ERROR:  QueryError: internal error: Expr error: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.D+{up to 6 digits}] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)`
2. We do not provide a full timestamptz feature compatible w/ pg. And we may not plan to offer it in the future. But this issue could be a reference when users find the differences of timestamptz between pg and RisingWave.

### To Reproduce

On pg:
```
test=# create table t (ts timestamptz);
CREATE TABLE
test=# insert into t values('2022-11-17 03:40:00');
INSERT 0 1
test=# insert into t values('2022-11-17 03:40:00Z+08:00');
INSERT 0 1
test=# select * from t;
           ts
------------------------
 2022-11-17 03:40:00+00
 2022-11-17 11:40:00+00
(2 rows)
```

On RisingWave:
```
dev=> create table t (ts timestamptz);
CREATE_TABLE
dev=> insert into t values('2022-11-17 03:40:00');
ERROR:  QueryError: internal error: Expr error: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.D+{up to 6 digits}] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)
dev=> insert into t values('2022-11-17 03:40:00Z+08:00');
ERROR:  QueryError: internal error: Expr error: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.D+{up to 6 digits}] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)
dev=> insert into t values('2022-11-17 03:40:00Z08:00');
```

### Expected behavior

Error info w/ correct column format.

**Comment by xiangjinwu** [comment]
Just for reference, PostgreSQL supports various formats:
https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-DATETIME-INPUT
https://www.postgresql.org/docs/current/datetime-input-rules.html

While we only support the following:
* `2022-11-17 11:40:00+08:00`
* `2022-11-17 03:40:00Z`
* `2022-11-17T11:40:00+08:00`
* `2022-11-17T03:40:00Z`

The cases mentioned in issue are actually more special:
* `2022-11-17 03:40:00` is not supported because its parsed values depends on environment (#5826).
* `2022-11-17 03:40:00Z+08:00` is actually malformed according to ISO 8601 or RFC 3339.
