### ISSUE TITLE
fix(datatype): Change occurences of `timestampz` to `timestamptz`

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#6475]
LGTM, however, note that postgres calls their function timestamptz (I guess tz standing for timezone), not timestampz, seems like we use timestampz in many places.

        Maybe we can correct it here or another PR. (EDIT: actually, this error is quite extensive: https://github.com/risingwavelabs/risingwave/search?q=timestampz). Anw, I guess its a minor chore, I'll create a low priority issue.

_Originally posted by @jon-chuang in https://github.com/risingwavelabs/risingwave/pull/6440#pullrequestreview-1187509870_
      
It's just a minor issue with naming. But actually we want `timestamptz` meaning timestamp time zone, not `timestampz`

**Comment by xiangjinwu** [comment]
Not sure why it was named `timestampz` initially, and I do agree keeping the name consistent would be less confusing. Just providing some relevant context:

Although the type is named `timestamp with time zone` in PG and RW, each datum does not store an associated time zone value in it. Instead, it always stores microseconds elapsed since epoch in UTC ([ref](https://www.postgresql.org/docs/current/datatype-datetime.html#:~:text=For%20timestamp%20with%20time%20zone%2C%20the%20internally%20stored%20value%20is%20always%20in%20UTC)). In other words, it is more like `TIMESTAMP_LTZ` in [Flink](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/types/#timestamp_ltz) rather than `TIMESTAMP WITH TIME ZONE` in [Flink](https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/types/#timestamp-with-time-zone).

Given that `Z` stands for UTC in ISO 8601 format, I feel like `timestampz` is a more meaningful internal name. But again, I agree being consistent with PG could be less confusing.

**Comment by ArshErgon** [comment]
@xiangjinwu so do we still need to change `timestampz` to `timestamptz`?

**Comment by jon-chuang** [comment]
Seems like there's no harm? @xiangjinwu

**Comment by fuyufjh** [comment]
Hi, @ArshErgon, any updates?

**Comment by ArshErgon** [comment]
Hey @fuyufjh, My apology I had exams and I was involve in other OS projects I completely  forgotten about this assignment.

**Comment by fuyufjh** [comment]
Don't worry. So will you continue the work?

**Comment by ArshErgon** [comment]
I already have given the PR, it just need a review.
If you want to work on it, go for it,
