### ISSUE TITLE
bug(frontend): cannot translate correlated subquery with `limit`

### ISSUE THREAD

**Issue by kwannoel** [risingwavelabs/risingwave#6605]
### Describe the bug

Seems like correlated subquery with `limit` cannot be translated. Is this feature planned?

### To Reproduce

```sql
create table t (v int);
SELECT
    1
FROM
    t
WHERE
    EXISTS (
      SELECT
        t.v
      LIMIT
        1
    );
drop table t;
```

```
ERROR:  QueryError: internal error: Subquery can not be unnested.
```

### Expected behavior
PG:
```
                        QUERY PLAN                         
-----------------------------------------------------------
 Result  (cost=0.01..35.51 rows=2550 width=4)
   One-Time Filter: $0
   InitPlan 1 (returns $0)
     ->  Result  (cost=0.00..0.01 rows=1 width=0)
   ->  Seq Scan on t  (cost=0.00..35.50 rows=2550 width=0)
(5 rows)

```

If planned for future, interim solution could be to return `NotImplementedError` instead.

**Comment by fuyufjh** [comment]
PG has nested-loop join but we don't have yet.

**Comment by fuyufjh** [comment]
@chenzl25 Could you explain more

**Comment by chenzl25** [comment]
Yes, there is an existing issue https://github.com/risingwavelabs/risingwave/issues/4204. Our subquery unnesting technique doesn't support transposing the apply operator and the limit operator, so in general we don't support correlated subquery once the correlated input ref is below the limit operator. As for your case, it is still possible, because the limit input is just a simple value and we can remove the limit operator.
