### ISSUE TITLE
bug: regress test sql file comment

### ISSUE THREAD

**Issue by curiosityyy** [risingwavelabs/risingwave#6719]
### Describe the bug

Adding a comment in SQL file in the regress test will fail the test. 
![image](https://user-images.githubusercontent.com/28347358/205477327-14362471-5b73-43d1-9df9-a3a8add07680.png)
![image](https://user-images.githubusercontent.com/28347358/205477341-2a76b866-018e-4f01-b77f-712b55231206.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/28347358/205477327-14362471-5b73-43d1-9df9-a3a8add07680.png)

Add line 98 in the above snapshot and run 
```
RUST_BACKTRACE=1 target/debug/risingwave_regress_test -h 127.0.0.1 \
  -p 4566 \
  -u root \
  --input `pwd`/src/tests/regress/data \
  --output `pwd`/src/tests/regress/output \
  --schedule `pwd`/src/tests/regress/data/schedule \
  --mode risingwave
```
The test will fail and it will run some SQL queries which are commented by `--@`.queries

### Expected behavior

The test pass.

### Additional context

Software:

    System Software Overview:

      System Version: macOS 12.3.1 (21E258)
      Kernel Version: Darwin 21.4.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal

**Comment by xiangjinwu** [comment]
This is expected behavior, but I agree the experience worth improvement if possible.

> it will run some SQL queries which are commented by `--@ ` queries

Not really. The comparison showing `-` at the beginning of each line means these lines are expected but not found in actual results. In other words, they are expected to be executed, but actually not.

So it is a problem of wrong expectation. The root cause here is: the test runner is unable to parse and understand the modified test files.

The test runner has some assumptions over the test files' format, but is unable to verify them and report parsing error. It misbehaves in this case.
* Each line in `sql/foo.sql` must has a corresponding line in `expected/foo.out`.

All files are ported from PostgreSQL are not meant to be modified a lot, except for commenting out individual test cases with `--@ `. All other modifications (incl. adding normal comments as in this issue) need to apply to both `sql/foo.sql` and `expected/foo.out` at the same time.

Better suggestions to improve this experience is welcomed. If not, I will just update the regress test README to make it clearer.
