### ISSUE TITLE
feat: support service discovery in meta client

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#6755]
### Is your feature request related to a problem? Please describe.

1. support connecting to multiple meta-node.
2. refresh leader address periodically or via error RPC response from standby node.

**Comment by CAJan93** [comment]
I will not implement the client side as part of this issue, as it is part of https://github.com/risingwavelabs/risingwave/issues/6755.

**Comment by yezizp2012** [comment]
> I will not implement the client side as part of this issue, as it is part of #6755.

?

**Comment by CAJan93** [comment]
Sorry. Part of https://github.com/risingwavelabs/risingwave/issues/6787. I just saw that the tracking issue was changed and that this issue should include the client implementation. Are we sure we want to do that? The current PR changes only the server and not the client and has about 300 lines code changes (see https://github.com/risingwavelabs/risingwave/pull/7049). Think that is a nice size for a review.

**Comment by CAJan93** [comment]
As discussed in Slack, meta service discovery will work as follows: 

1. The client sends a request against the K8s meta service. The service will connect the client against any meta instance 
2. The client uses the `LeaderService` to retrieve the current leader AND a list of all other meta nodes 
3. The client caches addresses of the meta nodes and periodically update the stored list of meta nodes using the `LeaderService`
4. If all cached meta nodes are down, go to 1.

We will skip 1. in `risedev`, since that is not a K8s environment. In that case the different components just get a list of meta nodes and no new nodes will be created on failover.

**Comment by CAJan93** [comment]
> As discussed in Slack, meta service discovery will work as follows:

There was more discussion. This decision may be revoked.
