### ISSUE TITLE
bug: sstable files in L0 could not be compacted to base level

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#6896]
### Describe the bug

The data in Level 0 becomes more and more but it could not compact to next level. It would cause read performance decrease and the throughput of our system would also decrease.

**Comment by Li0k** [comment]
I did some tests locally and on ec2 (nexmark_q7 test), and found that the system's compaction trigger is not as expected.I found the following problems:

#### Describe

1.  all data is piled up in l0
    - 3000+ l0 files with 70+ sub-level
    
<img width="723" alt="image" src="https://user-images.githubusercontent.com/15023748/207531145-3d6b1fb7-7429-4d17-8e49-6d75f1dda581.png">

2.  system no longer triggers base_level_compaction, It can be observed from metrics that all base-level-compactions from 0 to 6 are rejected (skip-by-overlapping)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/15023748/207531648-249434ab-84b4-4e1b-bb60-b6b965aae96b.png">
   
#### Explore

1. The compaction of a sub-level layer is blocked, resulting in an increase in the number of layers, and the number of files in each layer is small, which does not meet the compact requirements. The overall write-amp is large and can only wait for the merger, so TierCompaction is blocked

2. BaseLevelCompaction is blocked by first overlapping sub-level. 
Due to the implementation of TierPicker, compact-task needs to meet the limitations of file_count and write_amp, which may lead to skipping the middle layer under the existing implementation.
In turn, the restrictive condition of BaseLevelPicker is triggered, so that BaseLevelCompaction can no longer be generated, as shown in the figure

<img width="899" alt="image" src="https://user-images.githubusercontent.com/15023748/207533212-05713a2a-d986-46e5-a9cb-5f3ee4aedb49.png">

<img width="980" alt="image" src="https://user-images.githubusercontent.com/15023748/207533262-49a839c7-4353-4dd5-b717-080f12bc5a55.png">
