### ISSUE TITLE
should not refuse to start when given parallelism is larger than the available one

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#7293]
The compute node refuses to start if the given `parallelism` from CLI args is larger than the one we obtained from `resource_util::total_cpu_available`.

https://github.com/risingwavelabs/risingwave/blob/c8323d58d18e4ec458b19857c4bbe5d7e0b7841d/src/compute/src/lib.rs#L119-L126

As `risedev` has a default value of `4` for this field, one can never launch the cluster on a machine with less than 4 CPU cores. 😄

https://github.com/risingwavelabs/risingwave/blob/c8323d58d18e4ec458b19857c4bbe5d7e0b7841d/risedev.yml#L622-L623

I don't this is much reasonable and a `warn` should be enough here. Also for the memory limit here. 🤔

**Comment by lmatz** [comment]
CPU is arguably true as it does not lead to fatal errors, but a question is what's the relation between `parallelism` and `number of CPUs?

Memory can lead to OOM, I feel a fool-proof double-check can prohibit problems in advance. Since they are both command-line arguments, they are expected to be easily changed.

**Comment by BugenZhao** [comment]
> but a question is what's the relation between `parallelism` and `number of CPUs`?

As we limit the parallelism of a fragment on some compute node to its `parallelism` config, and each actor can only utilize a single CPU core, so making it default to the number of CPUs makes kind of sense.

I'm mainly afraid that we obtain the wrong info from `resource_util` on some platforms and there's no way for the users to bypass this constraint without modifying the source code. 🥺

**Comment by lmatz** [comment]
>I'm mainly afraid that we obtain the wrong info from resource_util on some platforms

Good point! Let's include it in the release testing

**Comment by fuyufjh** [comment]
I think the panic is reasonable. The problem is only in the playground mode, which uses a hard-ed config (parallelism = 4). How about just removing this hard-coded config? I think it's okay to use all the available cores.

**Comment by BugenZhao** [comment]
For playground, we hard-code `--parallelism 4` for compute nodes.
https://github.com/risingwavelabs/risingwave/blob/b925ca9bed6acbacd1460cc479e9b70d38d4e9c5/src/cmd_all/src/playground.rs#L74-L75
We may
- remove this so that the compute node will start with the parallelism from `total_cpu_avaliable()`,
- or allow specifying parallelism in `playground` CLI args.

For `risedev-dev`, we hard-code `parallelism: 4` in the default configuration.
https://github.com/risingwavelabs/risingwave/blob/c8323d58d18e4ec458b19857c4bbe5d7e0b7841d/risedev.yml#L622-L623
We may remove this so that the compute node will start with the parallelism from `total_cpu_avaliable()`, and specify it in `config/ci.toml`.

cc @xxchan Any ideas? 👀

**Comment by xxchan** [comment]
For `playground`, we only have the hard-coded parallelism for `playground-3cn`, so I think whether or not to remove it are both ok. 🤣

---

For `risedev`, IIRC we can only specify `parallelism` as (compute node's) CLI arg instead of configuration now (https://github.com/risingwavelabs/risingwave/issues/6742). So we have to write that in `risedev.yml`.

Things may change since we are doing system params refactoring. But I checked the code and some discussions and guess it's still the case:

- https://github.com/risingwavelabs/risingwave/pull/7613#discussion_r1092742674
- https://github.com/risingwavelabs/rfcs/pull/34#discussion_r1069061515
- https://github.com/risingwavelabs/risingwave/blob/405506f78683596ffd6510fa4a3e0caac9e200d1/src/compute/src/lib.rs#L91-L96
