### ISSUE TITLE
pgwire panics when SSL certificate verify failed

### ISSUE THREAD

**Issue by xxchan** [risingwavelabs/risingwave#7331]
### To Reproduce

When there's a `~/.postgresql/root.crt` (either other db's, or simply an empty file), connecting to risingwave makes it panic.

```
thread 'risingwave-main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/xxchan/Projects/risingwave/src/utils/pgwire/src/pg_protocol.rs:603:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/panicking.rs:111:5
   3: core::option::Option<T>::unwrap
             at /rustc/bdb07a8ec8e77aa10fb84fae1d4ff71c21180bb4/library/core/src/option.rs:778:21
   4: pgwire::pg_protocol::PgStream<S>::flush::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:601:9
   5: pgwire::pg_protocol::Conn<S>::flush::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:692:46
   6: pgwire::pg_protocol::PgProtocol<S,SM,VS>::do_process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:175:44
   7: pgwire::pg_protocol::PgProtocol<S,SM,VS>::process::{{closure}}
             at ./src/utils/pgwire/src/pg_protocol.rs:154:29
   8: pgwire::pg_server::handle_connection::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:147:44
   9: pgwire::pg_server::handle_connection::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:131:1
  10: pgwire::pg_server::pg_serve::{{closure}}::{{closure}}
             at ./src/utils/pgwire/src/pg_server.rs:118:40
```

**Comment by BowenXiao1999** [comment]
Yes, it is because when turn into ssl, we will take the original stream and store it as new ssl stream.

https://github.com/risingwavelabs/risingwave/blob/e940c7712b2804b15981892cb69ba19a4303e353/src/utils/pgwire/src/pg_protocol.rs#L631

Elegant way may be refactor,do not store the stream inside PgProtocol, because it will make such mutation hard to implement. Just like Materialize, return the stream and pass it in as arguments in each `process`. For detail, check out the permalink below. But this may not solve this issue.

The fast way I guess is remove the Ssl Error from here, do not flush, just return true and log the error instead.
https://github.com/risingwavelabs/risingwave/blob/e940c7712b2804b15981892cb69ba19a4303e353/src/utils/pgwire/src/pg_protocol.rs#L170-L178

Because the stream is None so we can not flush. But this will make user do not aware what happened, unless they check the log (not sure, have not tried it). so it maybe strange...

But seems Mz also return a Error and this error is not returned back to user, they just debug! the error
https://github.com/MaterializeInc/materialize/blob/bb6b6ef7de16fa9d45b7e8cae49afa2d0f55b52f/src/pgwire/src/server.rs#L151-L160
