### ISSUE TITLE
pg_stat_activity not giving active queries

### ISSUE THREAD

**Issue by abhyuday26** [risingwavelabs/risingwave#7514]
### Describe the bug

I am using Risingwave version 0.1.16.
`SELECT * FROM pg_stat_activity ;` doesn't give any expected output even when a query is executed in another terminal.

### To Reproduce

- Login into the machine using the below command:
   >  psql "postgres://dev:dev@rls-apse1-eks-a.risingwave-cloud.xyz:4566/dev?options=--tenant%3Drwc-6-releasetenant"

- After that, create the record:
  >  CREATE TABLE testtable AS SELECT generate_series(1, 10000000,1);

- Now to get the pid of the running query run the below query on the same machine from a different terminal (make sure you execute it before the execution of the above query is complete).
 > SELECT * FROM pg_stat_activity ;

### Expected behavior
pg_stat_activity should have returned the pid and other information of the running query

**Comment by xxchan** [comment]
> unsupported function: "pg_teminate_backend"

This is a typo

**Comment by xxchan** [comment]
IIUC #7274 only provides a dummy implementation for `pg_stat_activity`, and functions like `pg_terminate_backend`. You could take a look at the code, which is very simple.

**Comment by CAJan93** [comment]
> This is a typo

Thanks for supplying [feat(binder): hint similar candidates when function is unknown](https://github.com/risingwavelabs/risingwave/pull/7521). I think catching typos and minor issues early will be a great improvement 👍

**Comment by yezizp2012** [comment]
Currently In order to integrate some other ecological tools and implement some psql commands, we have several dummy implementation of system tables/functions including `pg_stat_activity` and `pg_terminate_backend`. It's not that easy to fully support activity-related functions in the current architecture, especially under multi-frontend deployment. Need more design and let's keep it to record.
