### ISSUE TITLE
Discussion: when should `create MV/sink` return OK?

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7593]
Right now, `create MV` and `create sink` can take a lot of time as they need to catch up with existing upstream data.

This is required as we don't want users to read stale data, e.g. a batch query issued against an MV that has not caught up with current progress.

The new proposal is that since`create SINK` has no MV and cannot be read, it does not require `catching up with current progress` and then returning an OK message to the user.

But for `create MV`, it is unclear whether we should wait?

The arguments for waiting are:
1. it is the default behavior of a traditional database that has materialized view, e.g. PG
2. users have consistent results across different MVs.

The arguments for not waiting are:
1. we can ensure consistency by not letting user issue batch queries against an MV that has not caught up with current progress.
2. if the user uses `psql`, then the user has to wait for the statement to be successful before exiting psql, which may take a lot of time.
3. Based on the feedback from multiple people(Devs and POC users), it seems it is somehow naturally assumed that this statement should finish quickly. People are confused about why it takes so much time.

Notice that #7418 was proposed to let users be aware of the progress of `catching up`.

Welcome any input.

**Comment by xxchan** [comment]
btw, this would conflict with https://github.com/risingwavelabs/risingwave/issues/6488

**Comment by BugenZhao** [comment]
Weak -1, especially for MV. Asynchronous DDL seems not to be a correct default behavior for **databases**. For those distributed OLTP databases, it's also common that adding an index lasts hours or days to complete, while the DDL statement in the SQL client will also be blocked for that time.

I guess what we really want is the management utilities for ongoing DDLs, by which we can monitor the progress, cancel them if required, or resume them from recovery so that users don't need to worry about the long running time.


> Based on the feedback from multiple people(Devs and POC users), it seems it is somehow naturally assumed that this statement should finish quickly. People are confused about why it takes so much time.

This is like Flink's behavior. 😄 Async completion of the Flink's job makes sense, as the semantics of `INSERT INTO ...` is just "spawn a background task to do this transformation continuously". As a result, querying the inconsistent results is also acceptable as nobody guarantees the background is done.

However, the concept we adopt is SQL's `MATERIALIZED VIEW`, which is well-defined in traditional databases. Even if we allow the DDL to finish asynchronously, this seems to bring not many benefits as the users is not able to query or create new materialized view on it. 🤔

**Comment by liurenjie1024** [comment]
I'm fine with complete as soon as possible, but we should return a message to say that `this means job has started to run`.
