### ISSUE TITLE
implement array_distinct

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#7765]
https://docs.databricks.com/sql/language-manual/functions/array_distinct.html
https://docs.snowflake.com/en/sql-reference/functions/array_distinct.html

Requested by POC

**Comment by CAJan93** [comment]
Who is POC? I only know this as "proof of concept" 😓

**Comment by lmatz** [comment]
> Who is POC? I only know this as "proof of concept" 😓

You are right!

**Comment by xiangjinwu** [comment]
> we don't support "array" function as the constructor

It is an array-constructing subquery. And the workaround is to use `array_agg`:
```
select array_agg(v1) from (select distinct unnest(array[1,1,2,3,1])) x(v1);
```

Due to a bug #7812 when ProjectSet (select-unnest) and Distinct used together, we need another workaround in current version to use from-unnest instead of select-unnest:
```
select array_agg(v1) from (select distinct * from unnest(array[1,1,2,3,1]) y) x(v1);
```

That being said, I also agree having a dedicated `array_distinct` is more user friendly.

**Comment by snipekill** [comment]
Hey @lmatz  Can I work on this issue?

**Comment by lmatz** [comment]
> Hey @lmatz Can I work on this issue?

Sure! @snipekill

**Comment by snipekill** [comment]
Hey @lmatz can you share a starting point or relevant code pointer on where to start? Thanks

**Comment by xiangjinwu** [comment]
Thanks for your interest. `array_distinct` would both take array as input and return array as output, for all element types. This is similar to `array_prepend`, which we already implemented. You can take it as a reference.

**Comment by lmatz** [comment]
@snipekill 
Right, besides `array_prepend`, you can also take a look at a recent PR that implements an array function `array_to_string` aka `array_join`: https://github.com/risingwavelabs/risingwave/pull/8027/files

**Comment by fuyufjh** [comment]
Hi, @snipekill May I ask the progress? Please let me know if you need any help.

**Comment by snipekill** [comment]
Sorry for the delay @fuyufjh. I read the PR for array_to_string and have understood the three main functions that need to be implemented are:- `try_from`, `eval` and `eval_row`, I have implemented the try_from function, but I was a bit confused on how to implement the eval functions. We do need a hash map to account for the distinct values.

Q1. What script do we need to run, so that our new expression gets added in the file `dashboard/proto/gen/expr.ts`

Q2. Can I get some documents on abstractions of variables, like Arc<ArrayImpl> and <ScalarRef>, how we can extract values from these abstractions. I did read the code of array_to_string PR, but I was a bit confused in how to get the values of Input Chunk. The structure of the Expression type could be simple, having elementType and elements which can be constructed in try_from function

Thanks

**Comment by fuyufjh** [comment]
Q1. See https://github.com/risingwavelabs/risingwave/blob/main/dashboard/README.md

Q2. `Arc` is an essential part of Rust, you may learn it from any Rust textbook like [Rust by Example](https://doc.rust-lang.org/rust-by-example/std/arc.html).

**Comment by snipekill** [comment]
@fuyufjh Can you check once, I have raised the PR, I will be adding integration test and check for refactoring and updating the comments as well to mention basic use case.

**Comment by fuyufjh** [comment]
> @fuyufjh Can you check once, I have raised the PR, I will be adding integration test and check for refactoring and updating the comments as well to mention basic use case.

COOL! Thanks for your work!
