### ISSUE TITLE
bug: constant parse error should be exposed

### ISSUE THREAD

**Issue by idx0-dev** [risingwavelabs/risingwave#7782]
### To Reproduce

The following SQL runs without errors.
```sql
SELECT
	count(*) AS failures,
	count(*) != 0 AS should_warn,
	count(*) != 0 AS should_error
FROM (
	SELECT
		bool 'x' AS TRUE) dbt_internal_test;
```
And result is:
```
failures	should_warn	should_error
1	true	true
```

### Expected behavior

It should panic with a Query Error like
```
Query 1 ERROR: ERROR:  invalid input syntax for type boolean: "x"
LINE 7:   bool 'x' AS TRUE) dbt_internal_test;
               ^
```

PostgreSQL 14.6

**Comment by xiangjinwu** [comment]
This is due to different evaluation / optimization order.

In PostgreSQL, the constant `bool 'x'` (or `2147483647 + 1` that overflows) is evaluated eagerly, and the error is reported before executing the query.

In current RisingWave, we look at the root query and found that `count(*)` does not need evaluation of 0th column, so it is pruned away.

Even after we enable constant folding, we may still not match PostgreSQL on such cases exactly. #4235
