### ISSUE TITLE
Longevity job is getting error "Storage error: Hummock error: ReadCurrentEpoch error Cannot read when cluster is under recovery"

### ISSUE THREAD

**Issue by sushantgupta** [risingwavelabs/risingwave#7841]
### Describe the bug

Recent longevity is getting error "Storage error: Hummock error: ReadCurrentEpoch error Cannot read when cluster is under recovery" while executing "select * from <MV> LIMIT 1" query.

Job Details:
https://buildkite.com/risingwave-test/longevity-test/builds/359#01863c49-2ff3-4ded-8e38-821bd2136889

Step/timeline:
1) 17:08 UTC: created materialized view q22,q101,q102 with 'STREAMING_PARALLELISM=3'.

2) 18:38 UTC: Able to fetch the records from materialized view.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/7961084/218246967-d03ef6fd-eb7d-4644-a068-1ad9823cb7f4.png">

3)19:08 UTC: now we are unable to fetch the data from materialized view and getting "**Storage error: Hummock error: ReadCurrentEpoch error Cannot read when cluster is under recovery**" error.

But, There was not a single pod crash.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/7961084/218247251-2637204a-e431-4eaa-a116-7c30b1d6b072.png">

**Comment by hzxa21** [comment]
This error is expected when there are queries running in `VISIBILITY_MODE=all` (by default) during recovery because CN's in-memory states will be clear on recovery, which will result in incorrect result in some cases for `VISIBILITY_MODE=all` queries (See https://github.com/risingwavelabs/risingwave/pull/7188#issuecomment-1376718485)

We can retry the batch query after recovery is done.

**Comment by sumittal** [comment]
@hzxa21 As this error came with the default setting, what should be done to avoid such errors?

**Comment by fuyufjh** [comment]
> As this error came with the default setting, what should be done to avoid such errors?

This is expected after some node crashes and the cluster is recovering itself. But why node failed during the longevity test? @sumittal

**Comment by zwang28** [comment]
This error itself is expected as explained by Patrick.

The problem in this test is exactly same as rwc-3-longevity-20230208-170541: the cluster is never able to succeed recovery because:

- The meta node is restarted without any error log at 2023-02-10T18:43 UTC
- All worker node cannot reach the new meta node, thus is treated as expired nodes and removed from cluster by the new meta node 5min later (heartbeat).

**Comment by zwang28** [comment]
Two meta node co-exist? Their log duration overlaps.

**Comment by yezizp2012** [comment]
I'm taking a day off for something  today. @shanicky would you please help to TAL. 🙏

**Comment by lmatz** [comment]
maybe related?: 
1. #7753 
2. https://risingwave-labs.slack.com/archives/C0340PNL68P/p1675850610976089?thread_ts=1675841825.247139&cid=C0340PNL68P

**Comment by fuyufjh** [comment]
See https://github.com/risingwavelabs/risingwave/issues/7841#issuecomment-1426954710
