### ISSUE TITLE
bug: frequent recovery test timeout in main-cron and main job

### ISSUE THREAD

**Issue by yezizp2012** [risingwavelabs/risingwave#7979]
### Describe the bug

Reported in notification buildkite and appeared in main and main-cron job. But not found in PR job. The difference is that:

<table>
<tr>
	<td> Job
	<td> TEST_NUM
	<td> KILL_RATE
<tr>
	<td> main-cron
	<td> 12
	<td> 1.0
<tr>
	<td> main
	<td> 16
	<td> 0.5
<tr>
	<td> PR
	<td> 8
	<td> 0.5
</table>

Firstly I though it was caused by heavy workload compared to PR job. But after some test in #7970 , decreasing `TEST_NUM` did not help, the batch test still timeout. And there will always be one test that timeout. Need more investigation.

**Comment by yezizp2012** [comment]
Cc @wangrunji0408

**Comment by wangrunji0408** [comment]
I guess the batch test timeout was caused by blocking (CPU is idle at this time). I also got a report from @Li0k today that a similar phenomenon occurred in his PR. ([link](https://buildkite.com/risingwavelabs/pull-request/builds/17548#0186590a-67a0-4e03-b297-b118aeff8e0d)) After debugging for a while, I still couldn't locate the blocking point. Need more investigation. Perhaps I should add something to madsim in order to better deal with it.

**Comment by wangrunji0408** [comment]
I found the blockings were caused by a bug in madsim. When killing a node, it may cause a cascade drop for the tasks of this node, where there will be a reentrancy of a lock in the call stack. This way, the program gets stuck in a deadlock :(
I'm trying to fix this bug in madsim by breaking the cascade drop. 🥵
