### ISSUE TITLE
test(perf): Check for performance regressions in microbenchmarks

### ISSUE THREAD

**Issue by jon-chuang** [risingwavelabs/risingwave#8033]
We will have more microbenchmarks now. e.g. expr framework and query plan generation (https://github.com/risingwavelabs/risingwave/issues/8031). 

We should integrate perf regression detection into CI and decide on a regression testing threshold (e.g. 10%). 

To avoid flakey or ineffective tests, we need a way to handle the general case (fixed threshold) and specific case (per-bench threshold when the general case is too strict or loose resp.).  

Hopefully, with a framework like criterion, we can reduce the dependence on manually specifying the threshold. But I'm afraid that criterion runs too many iterations and would be slow and expensive.

Note that we should not run anything more than _microbenchmark_ (single-thread, completely in-memory and no IO) regression test in CI. It will likely be flakey.

Bench is run in release mode, of course. 

@lmatz @kwannoel

**Comment by lmatz** [comment]
I don't mind not having a threshold first. We can first let the results be integrated into the performance dashboard.

Since the criterion can output in CSV format, integration should be easy.

After running for a while, we learn what the threshold should be, and this is also part of @cyliu0 's current task, i.e. alert when the performance regresses. `threshold` is hard to be set without a series of data points.

**Comment by fuyufjh** [comment]
Alerting has been introduced now.
