### ISSUE TITLE
bug :  SELECT TIMESTAMP 'now'; not working

### ISSUE THREAD

**Issue by abhyuday26** [risingwavelabs/risingwave#8105]
### Describe the bug

As per #7686 we should get same result for these three queries
```
SELECT CURRENT_TIMESTAMP;
SELECT now();
SELECT TIMESTAMP 'now';
```

But we encounter below error

>`ERROR:  QueryError: Expr error: Parse error: Can't cast string to timestamp (expected format is YYYY-MM-DD HH:MM:SS[.D+{up to 6 digits}] or YYYY-MM-DD HH:MM or YYYY-MM-DD or ISO 8601 format)
`

Support for above two queries was given in #7695

### To Reproduce

It can be simply reproduced by running this query.
`SELECT TIMESTAMP 'now'; `

### Expected behavior

It should return the current timestamp.
```
         timestamp
----------------------------
 2023-02-21 19:26:33.361002
(1 row)
```

**Comment by xiangjinwu** [comment]
Yes, `TIMESTAMP 'now'` is not implemented right now.

However, even though `SELECT TIMESTAMP 'now';`, `SELECT now();` and `SELECT CURRENT_TIMESTAMP;` are expected to return the same result as a batch query, they have different meaning in (materialized) views. The `TIMESTAMP 'now'` form would be a constant equal to the time of view creation.

Let's treat this as a missing feature and decide whether we want to support it (and warn user) rather than a bug.
cc @neverchanje

**Comment by xiangjinwu** [comment]
until a valid use case occurs
