### ISSUE TITLE
RisingWave Dashboard loads very slowly

### ISSUE THREAD

**Issue by JuchangGit** [risingwavelabs/risingwave#8265]
![image](https://user-images.githubusercontent.com/34911052/222090825-843e06bf-53f2-470b-8d9b-0f869bdb3bf6.png)
How do I build RisingWave Dashboard myself ？

**Comment by BugenZhao** [comment]
> RisingWave Dashboard loads very slowly

This might be caused by failing to fetch data from the Prometheus server. Would you mind telling how you launched the cluster? If you're using RiseDev, do you also specify `prometheus` in the corresponding profile section in `risedev.yml`?

> How do I build RisingWave Dashboard myself ？

You can turn `ENABLE_BUILD_DASHBOARD_V2` on with `./risedev configure`.

**Comment by JuchangGit** [comment]
> 
cd risingwave-demo/docker
docker-compose up -d

**Comment by JuchangGit** [comment]
按照文档https://www.risingwave.dev/docs/current/risingwave-docker-compose/启动的集群

**Comment by TennyZhuang** [comment]
I’ll take a look

**Comment by JuchangGit** [comment]
Version 0.18 does not have this problem
