### ISSUE TITLE
bug(memory): unexpected memory consumption on Meta node

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave#8270]
In what situation the Meta Service can take 2 GB memory?
 
![image](https://user-images.githubusercontent.com/10192522/222125066-55f6a9bb-c4f8-4620-a92e-0c25ff815482.png)

Maybe related to the crash of compactor node? It happened 1 min after compactor node down (killed by k8s…. never mind, it’s another issue)

![image](https://user-images.githubusercontent.com/10192522/222125161-9c609abd-48a0-464c-a848-b9c62d844b47.png)

Slack thread: https://risingwave-labs.slack.com/archives/C0340PNL68P/p1677650307767649

**Comment by zwang28** [comment]
The leaking is from backtrace, which is first triggered when meta node writes [a log with backtrace](https://github.com/risingwavelabs/risingwave/blob/eb4356016ebf97800cd053e767de261ba71e8e6b/src/meta/src/hummock/compaction_scheduler.rs#L296):

#### The memory leaking is caused by backtrace:
The backtrace-rs will [cache addr2line::Context](https://github.com/rust-lang/backtrace-rs/blob/a3406f93f3e6d91e05525c671fa694a0aea22c82/src/symbolize/gimli.rs#L261). which can be large. 

We can prove it as follow:
1. `addr2line --exe risingwave`. This will create a context that loads risingwave, and wait for std input. So we can observe the memory now.
2. The RSS of addr2line process will be 400 MB. See [pmap-debug-info-uncompressed.txt](https://github.com/risingwavelabs/risingwave/files/10877965/pmap-debug-info-uncompressed.txt). 
 
Note that it's less than 2GB leaking in this issue.

#### Compressing debug info worsens the situation:
The test above uses a release build without compressing debug info. When we compress debug info and test again, the RSS os addr2line is now 2GB, which matches the issue. See [pmap-debug-info-compressed.txt](https://github.com/risingwavelabs/risingwave/files/10877964/pmap-debug-info-compressed.txt)

**Comment by fuyufjh** [comment]
Hmmm, but [L249](https://github.com/rust-lang/backtrace-rs/blob/a3406f93f3e6d91e05525c671fa694a0aea22c82/src/symbolize/gimli.rs#L249) shows the cache size is limited to 4.

And [L256](https://github.com/rust-lang/backtrace-rs/blob/a3406f93f3e6d91e05525c671fa694a0aea22c82/src/symbolize/gimli.rs#L256) also said it's "A very small, very simple LRU cache"

**Comment by zwang28** [comment]
> Hmmm, but [L249](https://github.com/rust-lang/backtrace-rs/blob/a3406f93f3e6d91e05525c671fa694a0aea22c82/src/symbolize/gimli.rs#L249) shows the cache size is limited to 4.
> 
> And [L256](https://github.com/rust-lang/backtrace-rs/blob/a3406f93f3e6d91e05525c671fa694a0aea22c82/src/symbolize/gimli.rs#L256) also said it's "A very small, very simple LRU cache"
> 
> 
> 

the cache itself is small, but the one cache item addr2line context is large.

**Comment by fuyufjh** [comment]
#8326 should fix this more or less. I'll close this first and let's reopen if necessary.
