### ISSUE TITLE
handle watermark in backfill

### ISSUE THREAD

**Issue by yuhao-su** [risingwavelabs/risingwave#8375]
A random thought, if a watermark column exists as the first column in the pk, can we emit the watermark when backfill? Even maybe we can do some optimization for backfill with that watermark?

_Originally posted by @st1page in https://github.com/risingwavelabs/risingwave/issues/7790#issuecomment-1423696233_

**Comment by chenzl25** [comment]
I found that it is almost impossible to emit a watermark even when the first column of the backfill executor is a watermark column because the value of the watermark column keeps increasing, so the backfill existing data will usually have a value lower than the upstream watermark. That is to say, no watermark should be sent downstream while performing backfill.
