### ISSUE TITLE
Discussion: refill data for block-cache after compaction

### ISSUE THREAD

**Issue by Little-Wallace** [risingwavelabs/risingwave#8553]
### Background
Every time we finish a compaction task, it will remove some sst files and add new files. It means that the data of those moved files in block-cache will be expired. And any query (include both get and iterator) with these block will wait IO request to remote storage and it really hurts the performance of our system. We can observe that the streaming throughput decrease after every large compaction task.

### Describe the solution you'd like

Refill some block to the block-cache before apply the new version-delta.

I do not have a good idea to identify which block shall be filled to cache. It is difficult to decide whether block will be accessed frequently in the future.

### Describe alternatives you've considered

Fill cache may cause other hot blocks are evicted early. Because we may fill data which would be never read to cache.

**Comment by lmatz** [comment]
Can I understand it in the following simplified way, after compaction:

1. if the number of new blocks/files is smaller than the number of useless blocks/files in the cache, then the situation is trivial(?), i.e. we replace the useless ones with the new ones.
2. if not, we find the new blocks/files whose key range contain the `first key` of the useless blocks/files in the cahce and then replace them. Since a single key must be included in only one block/file that is newly created by compaction, the strategy doesn't take more cache space, i.e. does not affect other hot blocks.    Why `first key`? Just a random and simple heuristic, since it was once in the cache.

**Comment by soundOfDestiny** [comment]
> Will we refill block cache? If not, what prevent us from doing so? If yes, what the refill policy is?

Not now. Because hot blocks vary over time.

> Will we refill meta cache? If not, what prevent us from doing so? If yes, what the refill policy is?

Yes. Compaction output which is corresponding with meta cache which was previously in cache will be refilled.
We have finished refilling meta cache in #8286 .

**Comment by Little-Wallace** [comment]
I refactor some strategy these weeks in https://github.com/Little-Wallace/risingwave/tree/refactor-cache.
But it is difficult to know which  data need to be refilled.
I think we shall refill sstable-file to disk-cache. Because disk-cache is large enough so that we can read more data and do not need to specify which block is hot.
