### ISSUE TITLE
streaming: adjust exchange buffer size (permit) dynamically based on the throughput

### ISSUE THREAD

**Issue by BugenZhao** [risingwavelabs/risingwave#8654]
Backgrounds:
- As explained in #6943 and #6571, to avoid unbounded barrier latency, we're not allowed to set a limit on the number of concurrent barriers.
- So when the computation is heavy or sinking into downstream external system performs poor, we'll have a stable high barrier latency, and its value will be exactly `in-flight barrier numbers * barrier interval`.
- This barrier latency is not only a result of the limited processing capacity of RisingWave for a complex query, but is also caused by **the large amount of data buffered in the exchange channel**.

Recall why we need buffering for exchanges: we need to ensure there's still data available to process in the downstream after an RTT of network latency, to avoid pipelining execution from stalling. In the case where the overall latency is already very high, we can definitely decrease the buffer size as the throughput is low, to prevent the situation from being worse. This can be achieved by adjusting the "permit"s (record num, #6170) in each exchange channel, based on the real-time throughput.

cc @hzxa21 @fuyufjh @lmatz

**Comment by kwannoel** [comment]
> but is also caused by the large amount of data buffered in the exchange channel.
How will this lead to high latency?

**Comment by lmatz** [comment]
> > but is also caused by the large amount of data buffered in the exchange channel.
> 
> How will this lead to high latency?

CMIIW, my understanding, 

There are two types of latency:
1. latency of a single row
2. latency of a barrier

(1) is not changed with/without this dynamic adjust, it simply depends on the real processing capacity of RisingWave.

But 2 can be adjusted as we can read fewer rows from the source if the barrier latency starts growing.
Now this should be solved by the natural backpressure due to all kinds of bounded channels (in-memory or over network) in the system, but if the channel size/the number of channels in sequence is too large, then the backpressure does not immediately giving "pressure" to the source actors if the actors at the end of a query is processing slowly.

By adjusting the buffer size to a smaller number, instead of buffering these rows within RW, we delay reading them from the upstream. (1) still not changed, but (2) looks better.

**Comment by lmatz** [comment]
Does a larger-than-expected buffer size slow the speed of `dropping a sink`?

**Comment by BugenZhao** [comment]
> Does a larger-than-expected buffer size slow the speed of `dropping a sink`?

I guess so, since all in-flight messages need to be processed before the `Stop` barrier. A large barrier latency leads to the large latency of dropping a streaming job as well.

It's also worth noting that in this way, the buffer is already cleaned before we actually dropping the executor structures, so it should have nothing to do with https://github.com/risingwavelabs/risingwave/pull/8624

> But does the reasoning apply to other in-memory channel?

Yes, we use the same mechanism for local and remote exchange to make it fair.

**Comment by BugenZhao** [comment]
Close in favor of #9427.
