### ISSUE TITLE
Implement date_part(text, interval)	

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#8817]
# Syntax

``` sql
DATE_PART(text, interval)
```

# Description

The `date_part` function in Postgres is used to extract a specific part
of a given interval, such as days, hours, minutes, months, or years.

# Parameters

  - `text`: The part of the interval to be extracted. It can be one of
    the following: *century*, *day*, *decade*, *hour*, *microsecond*,
    *millisecond*, *minute*, *month*, *quarter*, *second*, *week*,
    *year*, *timezone*, *timezone\_hour*, or *timezone\_minute*.

  - `interval`: The input interval value from which the specified part
    will be extracted.

# Returns

The function returns a numeric value representing the specified part of
the given interval.

# Examples

``` sql
SELECT DATE_PART('day', INTERVAL '5 days 4 hours'); -- Returns 5
SELECT DATE_PART('hour', INTERVAL '5 days 4 hours'); -- Returns 4
```

# See Also

  - `date_trunc`: Truncates a timestamp or interval value to a specified
    precision.

  - `extract`: Extracts a specific part of a timestamp or interval
    value, similar to `date_part`.

# Compatibility

The `date_part` function is compatible with PostgreSQL and is part of
the SQL standard.

# A real-world Example:

```sql
DATE_PART('day', CAST(s.expect_arrival_date AS TIMESTAMP) -
                        CAST(s.delivery_time AS TIMESTAMP))   
```

**Comment by CAJan93** [comment]
Do we want to support `date_part(text, timestamp)` or also `date_part(text, interval)` ([see PSQL docs](https://www.postgresql.org/docs/8.1/functions-datetime.html)).

**Comment by xiangjinwu** [comment]
The example above is actually requesting the latter, since `TIMESTAMP - TIMESTAMP` results in `interval`.

`date_part` should share the implementation with `extract`, or rewritten as `extract + cast` if performance is not a concern.

Our `extract` implementation is also missing support for many fields, as shown in the regress test:
https://github.com/risingwavelabs/risingwave/blob/d06346151ce13176856ffe0e173aeff60973fe45/src/tests/regress/data/sql/date.sql#L224
