### ISSUE TITLE
The mv on mv creation should response finished status only after a checkpoint barrier

### ISSUE THREAD

**Issue by chenzl25** [risingwavelabs/risingwave#9178]
Currently, the mv on mv creation responses finished status after a non-checkpoint barrier, but it is possible that a recovery occurs after the non-checkpoint and before a checkpoint barrier which appears to have the potential of resulting in some loss of data from the batch query side.

**Comment by yezizp2012** [comment]
Well, IIUC if the creating progress of MoM is reported as finished on a non-ckpt barrier, the related command will not be finished since it requires ckpt. And the barrier manager will force set ckpt for the next barrier, then the create MoM command will be finished in the next run. see more details here:

https://github.com/risingwavelabs/risingwave/blob/5354c564cab0b99b3aa88b11b5eb03eccccdddfe/src/meta/src/barrier/mod.rs#L195-L213
