### ISSUE TITLE
insertion not executed when insert returning const

### ISSUE THREAD

**Issue by broccoliSpicy** [risingwavelabs/risingwave#9188]
### To Reproduce
```sql
dev=> create table t (v1 int, v2 real);
CREATE_TABLE
dev=> insert into t (v2) values (1.5) returning 1.1;
 ?column? 
----------
      1.1
(1 row)

INSERT 0 1
dev=> select * from t;
 v1 | v2 
----+----
(0 rows)

dev=> explain insert into t (v2) values (1.5) returning 1.1;
              QUERY PLAN               
---------------------------------------
 BatchValues { rows: [[1.1:Decimal]] }
```

### Expected behavior

```sql
postgres=# create table t (v1 int, v2 real);
CREATE TABLE
postgres=# insert into t (v2) values (1.5) returning 1.1;
 ?column? 
----------
      1.1
(1 row)

INSERT 0 1
postgres=# select * from t;
 v1 | v2  
----+-----
    | 1.5
(1 row)
```

**Comment by BugenZhao** [comment]
This is a result of applying `TrivialProjectToValuesRule`:

https://github.com/risingwavelabs/risingwave/blob/46a27861e08ac512d95bba6c43c2ef8145616bc1/src/frontend/src/optimizer/rule/trivial_project_to_values_rule.rs#L21-L38

The original plan for `INSERT .. RETURNING <const>` is like:
```
 LogicalProject { exprs: [1:Int32] }
 └─LogicalInsert { table: t, returning: true }
   └─LogicalValues { rows: [[233:Int32]], schema: Schema { fields: [*VALUES*_0.column_0:Int32] } }
```

Since all expressions in the `Project` are constants, and we're sure about the row count of `Values`, this rule will apply and replace the whole plan with a single `Values`. This is also why we don't have this problem for `UPDATE` and `DELETE`: theirs is an extra `Scan` and the row count cannot be determined. 😄

So I suggest we add a new `PlanVisitor` to check if there's a side effect in the children. If so, we should not apply this rule.
