### ISSUE TITLE
risingwave hummock sdk does not print trace log

### ISSUE THREAD

**Issue by soundOfDestiny** [risingwavelabs/risingwave#9193]
### Describe the bug

https://github.com/risingwavelabs/risingwave/blob/4f438dd553c547f070b8b411e8da689acba1809f/src/utils/runtime/src/lib.rs#L162

**Comment by hzxa21** [comment]
As discussion offline, I think a better way to address this is to set the default log level to be INFO for release build. Example: https://github.com/risingwavelabs/risingwave/blob/4f438dd553c547f070b8b411e8da689acba1809f/src/utils/runtime/src/lib.rs#L166

Let's adpot this approach instead of enumerating all packages in https://github.com/risingwavelabs/risingwave/blob/4f438dd553c547f070b8b411e8da689acba1809f/src/utils/runtime/src/lib.rs#L162.
