### ISSUE TITLE
bug: 'primary_key' is allowed by sink types other than 'upsert'

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave#9443]
### Describe the bug

```
create sink invalid_pk_sink from t with (connector = 'blackhole', primary_key = 'v1');
```

### To Reproduce

As above.

### Expected behavior

We should only allow `primary_key` when `upsert` is enabled.

**Comment by xiangjinwu** [comment]
As far as I can tell from digging into the actual code implementation, there are 4 possible states of `type = ` for a sink today:
* `upsert`, which requires primary key.
* Unspecified or specified to an unrecognized value. This is the case for the example statement above (blackhole), as well as [elasticsearch](https://github.com/risingwavelabs/risingwave/blob/2607ae77999760fd2d66b101a866aaabc189be4b/e2e_test/sink/elasticsearch/elasticsearch_sink.slt#L5-L11) sink. It will actually default the `SinkType` enum to upsert ([src](https://github.com/risingwavelabs/risingwave/blob/2607ae77999760fd2d66b101a866aaabc189be4b/src/frontend/src/optimizer/plan_node/stream_sink.rs#L246-L268)). This is likely a bug and we would require `format xxx` soon under the new syntax. We need to clarify the actual behavior, connector by connector, for example:
  * blackhole seems to act as if append-only, when unspecified. Then `primary_key` is unnecessary.
  * elasticsearch seems to act as if upsert, when unspecificed. Then `primary_key` should actually be required.
* `debezium`, which also requires primary key ([src](https://github.com/risingwavelabs/risingwave/blob/2607ae77999760fd2d66b101a866aaabc189be4b/src/connector/src/sink/kafka.rs#L322-L328)). Due to the same logic above, its `SinkType` is still `upsert`.
* `append-only`. In the current implementation, providing `primary_key` does make a difference:
  * Without `primary_key`, the all kafka messages would have key = `{}` (empty json object) and they would be sent to same kafka partition, leading to data skew.
  * With `primary_key`, the values of these columns would be included in kafka key, which is then hashed to decide which kafka partition a message should write to.
  * Practically, empty `primary_key` is allowed but is bad practice right now. We shall first fix the behavior to round-robin before disallowing `primary_key` here. Or do we still want to give user the ability to select partition based on some columns, even when the sink is append-only?

@neverchanje @tabVersion Could you help clarify what should we do in each cases?

**Comment by tabVersion** [comment]
Here are my thoughts.

* `connector = 'es'` only works with `format upsert encode native`, and I think it always works in an upsert way so `primary_key` is required.
* `connector = 'blackhole'` does nothing (works with `format append_only encode native`). I am ok with seeing it as append-only. So we should reject `primary_key` in this case, jusr for `blackhole` sink. 
* `connector = mq` and `format debezium encode json/avro/protobuf` is another case of `upsert` and `primary_key` is required.

Overall, we are going to require `primary_key` for `upsert` and `debezium` format but I want to make it optional for `append-only` format. I've seen requirements that user just wants to partition the data by some column and we can offer the  ability without effort. 

> Without primary_key, the all kafka messages would have key = {} (empty json object) and they would be sent to same kafka partition, leading to data skew.

Not true, Kafka will use Round Robin for these messages and I don't think there is data skew.

**Comment by xiangjinwu** [comment]
> Not true, Kafka will use Round Robin for these messages and I don't think there is data skew.

Kafka would use Round Robin when key is unset. But our current implementation always sets key = `{}` (2 bytes). This is a minor implementation bug we need to fix.

**Comment by tabVersion** [comment]
> > Not true, Kafka will use Round Robin for these messages and I don't think there is data skew.
> 
> Kafka would use Round Robin when key is unset. But our current implementation always sets key = {} (2 bytes). This is a minor implementation bug we need to fix.

OMG, that's a bug indeed.

**Comment by xiangjinwu** [comment]
Seems to be a misunderstanding because #9768 was not done.

**Comment by fuyufjh** [comment]
> > > Not true, Kafka will use Round Robin for these messages and I don't think there is data skew.
> > 
> > 
> > Kafka would use Round Robin when key is unset. But our current implementation always sets key = {} (2 bytes). This is a minor implementation bug we need to fix.
> 
> OMG, that's a bug indeed.

Let's follow this?

https://github.com/apache/kafka/blob/f1e58a35d7aebbe72844faf3e5019d9aa7a85e4a/clients/src/main/java/org/apache/kafka/clients/producer/internals/DefaultPartitioner.java#L28-L32

**Comment by fuyufjh** [comment]
Seems nothing else to do
