### ISSUE TITLE
alter source rename on a table fails

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave#9540]
### Describe the bug

```
dev=> CREATE TABLE s3_table (
dev(>     kaito_user_id varchar,
dev(>     event_type_id int,
dev(>     event_date varchar,
dev(>     event_id varchar,
dev(>     dw_creation_date Timestamptz AS PROCTIME()
dev(> ) WITH (
dev(>     connector = 's3',
dev(>     s3.region_name = 'us-west-2',
dev(>     ......
dev(> ) ROW FORMAT JSON;
CREATE_TABLE
dev=> alter source s3_table to s4_table;
CREATE_TABLE
dev=> alter source s3_table rename to s4_table;
ALTER_SOURCE
dev=> \d
                      List of relations
   Schema   |        Name        |       Type        | Owner 
------------+--------------------+-------------------+-------
 public         | s3_table                    | table             | root
 rw_catalog | rw_ddl_progress       | table             | root
 rw_catalog | rw_meta_snapshot   | table             | root
 rw_catalog | rw_relation_info        | table             | root
(11 rows)

dev=> select count(*) from s4_table;
ERROR:  QueryError: Expr error: Context not found
dev=> drop table s3_table;
DROP_TABLE
```

**Comment by BugenZhao** [comment]
There're two bugs here:

1. By creating a table with a connector, we create two objects (`source` and `table`) with the same name. Normally the source should be "shadowed" by the table, but it seems we fail to check it for `ALTER SOURCE`. So by `ALTER SOURCE` we rename the underlying source while keeping the table name untouched, which should be rejected.
2. Since the source is exposed after renaming, `SELECT FROM s4_table` actually performs a source-select, where the `PROCTIME` is unhandled to be rewritten to a constant. That's why we get the error of `Context not found` since by default we extract the timestamp from the current epoch value, which is only valid in streaming execution.

**Comment by BugenZhao** [comment]
Will open a new issue for the latter bug.
