### ISSUE TITLE
bug: create mv on nexmark stuck sometimes 

### ISSUE THREAD

**Issue by ZENOTME** [risingwavelabs/risingwave#9631]
### Describe the bug

I try to create mv on nexmark source and find that sometime it will be stuck. 

(I guess it may relate to the nexmark source, such as it will continue to generate data so that create mv on it will be slow?

It's a normal phenomenon?

## enviroment

machine: m1 pro 
start command: `./risedev dev ci-3cn-1fe`

## stuck case 1
```
/// terminal stuck
~/Project/risingwave-test/longevity/nexmark main* 7s
❯ psql -h localhost -p 4566 -d dev -U root -f base_config.sql
SET_VARIABLE
CREATE_TABLE
CREATE_TABLE
CREATE_TABLE

~/Project/risingwave-test/longevity/nexmark main*
❯ psql -h localhost -p 4566 -d dev -U root -f queries/q1.sql
SET_VARIABLE <--- stuck here 

/// frontend 
WARN risingwave_frontend::session: slow query has been running for another 60s sql_str="CREATE MATERIALIZED VIEW nexmark_q1 AS SELECT auction, bidder, 0.908 * price AS price, date_time FROM bid"
```

### stuck case2 

```
~/Project/risingwave-test/longevity/nexmark main*
❯ psql -h localhost -p 4566 -d dev -U root -f base_config.sql
SET_VARIABLE
CREATE_TABLE
CREATE_TABLE
CREATE_TABLE

~/Project/risingwave-test/longevity/nexmark main*
❯ psql -h localhost -p 4566 -d dev -U root -f queries/q1.sql
SET_VARIABLE
CREATE_MATERIALIZED_VIEW

~/Project/risingwave-test/longevity/nexmark main*
❯ psql -h localhost -p 4566 -d dev -U root -f queries/q2.sql
SET_VARIABLE
CREATE_MATERIALIZED_VIEW

~/Project/risingwave-test/longevity/nexmark main*
❯ psql -h localhost -p 4566 -d dev -U root -f queries/q3.sql
SET_VARIABLE
CREATE_MATERIALIZED_VIEW

~/Project/risingwave-test/longevity/nexmark main*
❯ psql -h localhost -p 4566 -d dev -U root -f queries/q4.sql
SET_VARIABLE <--- stuck here 

```

### file used 

```
// base_config.sql
SET STREAMING_PARALLELISM=3;
CREATE TABLE person (
    "id" BIGINT,
    "name" VARCHAR,
    "email_address" VARCHAR,
    "credit_card" VARCHAR,
    "city" VARCHAR,
    "state" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR,
    PRIMARY KEY (id)
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Person',
    nexmark.split.num = '12',
    nexmark.min.event.gap.in.ns = '50000'
);

CREATE TABLE auction (
    "id" BIGINT,
    "item_name" VARCHAR,
    "description" VARCHAR,
    "initial_bid" BIGINT,
    "reserve" BIGINT,
    "date_time" TIMESTAMP,
    "expires" TIMESTAMP,
    "seller" BIGINT,
    "category" BIGINT,
    "extra" VARCHAR,
    PRIMARY KEY (id)
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Auction',
    nexmark.split.num = '12',
    nexmark.min.event.gap.in.ns = '50000'
);

CREATE TABLE bid (
    "auction" BIGINT,
    "bidder" BIGINT,
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR,
    "date_time" TIMESTAMP,
    "extra" VARCHAR
) with (
    connector = 'nexmark',
    nexmark.table.type = 'Bid',
    nexmark.split.num = '12',
    nexmark.min.event.gap.in.ns = '50000'
);

```

```
// q1.sql
CREATE MATERIALIZED VIEW nexmark_q1
AS
SELECT
    auction,
    bidder,
    0.908 * price as price,
    date_time
FROM bid;
```
more file can refer: https://github.com/risingwavelabs/risingwave-test/tree/main/longevity/nexmark

### To Reproduce

described in stuck case

**Comment by BugenZhao** [comment]
Would you please check the await-tree dump in the dashboard(`:5691`) or with `risedev ctl trace`?

**Comment by BugenZhao** [comment]
I've tried to reproduce this locally but found there's no stuck but the Backfill executor is too slow to catch up with the progress of the `bid` source. 🤣

This can be verified by the dashboard or `rw_ddl_progress`.

<img width="1624" alt="Screenshot 2023-05-12 at 2 26 46 PM" src="https://github.com/risingwavelabs/risingwave/assets/25862682/2d0e3f21-dd4e-4439-825e-dda59e5d73f3">
<img width="1624" alt="Screenshot 2023-05-12 at 2 26 55 PM" src="https://github.com/risingwavelabs/risingwave/assets/25862682/154eefe6-d427-478a-8f99-fd7cc75d9ebe">

This is not a problem in production, as...
- With an optimized build, the throughput of our system is much higher and may not reach the bottleneck. As the data generation is limited to `1_000_000_000 / 50_000 = 20_000` rows per sec, the downstream materialized view can always catch up with the upstream.
- Since the back-pressure of Backfill is kind of weak, there's really no way to avoid this live-lock from happening under a heavy workload. We should encourage users to scale out the MV creation. cc @chenzl25

**Comment by chenzl25** [comment]
`base_config.sql` still used `table` instead of `source` to test nexmark, but we have already migrated to use `source`.  https://github.com/risingwavelabs/risingwave/blob/e31f15c1b93cecca5401d8d05d73e7d7a639383f/e2e_test/nexmark/create_sources.slt.part
