### ISSUE TITLE
Do we want to panic if we get an incorrect scaling request?

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave#9940]
### Describe the bug

If we send meta a misconfigured scaling request, then meta panics (see [here](https://github.com/risingwavelabs/risingwave/blob/03d6985ca14b74c5f5d54a4fb1545b6b23a93231/src/meta/src/stream/scale.rs#L134)). In our cloud setup this would lead to a restart of the meta pod and a failover to the follower. 

Do we really want to use this in prod? Do we disable these assertions in prod? Maybe it is safer to just block the request and return an error. 

```rs
pub(crate) fn rebalance_actor_vnode(
    actors: &[StreamActor],
    actors_to_remove: &BTreeSet<ActorId>,
    actors_to_create: &BTreeSet<ActorId>,
) -> HashMap<ActorId, Bitmap> {
    assert!(actors.len() >= actors_to_remove.len());

    let target_actor_count = actors.len() - actors_to_remove.len() + actors_to_create.len();
    assert!(target_actor_count > 0);
```

CC @ALeitert @shan

**Comment by lmatz** [comment]
+1 for validating the request, reject and return error if it is wrong,
I guess the general principle is to avoid any panic/fatal error that crashes any component of RW in a production environment

**Comment by BugenZhao** [comment]
Since we divide the scaling interface for cloud into two RPCs: `cluster_info` and `reschedule`, it's possible that there're some races during two calls. So `reschedule` is designed to be as defensive as possible for the requests.

This function is not the entry point for scaling. Actually, a complete set of validations have been done in `build_reschedule_context` and other places.

https://github.com/risingwavelabs/risingwave/blob/318714b2a50befdb42cd7ec9e4c6590dd43d9e6d/src/meta/src/stream/scale.rs#L488-L519

https://github.com/risingwavelabs/risingwave/blob/318714b2a50befdb42cd7ec9e4c6590dd43d9e6d/src/meta/src/stream/scale.rs#L641-L646

May I ask if there are edge cases we don't cover in practice?
